demos-europe/demosplan-ui

- .babelrc
- package.json
- src/components/core/DpButtonRow.vue
- src/components/core/DpChangeStateAtDate.vue
- src/components/core/DpDashboardTaskCard.vue
- src/components/core/DpDataTable/DpDataTable.vue
- src/components/core/DpDataTable/DpTableHeader.vue
- src/components/core/DpDataTable/DpTableRow.vue
- src/components/core/DpDataTable/DpWrapTrigger.vue
- src/components/core/DpEditor/DpEditor.vue
- src/components/core/DpEditor/DpLinkModal.vue
- src/components/core/DpEditor/DpRecommendationModal.vue
- src/components/core/DpEditor/DpUploadModal.vue
- src/components/core/DpInlineNotification.vue
- src/components/core/DpModal.vue
- src/components/core/DpResettableInput.vue
- src/components/core/DpSlidebar.vue
- src/components/core/DpTextWrapper.vue
- src/components/core/DpTransitionExpand.vue
- src/components/core/DpTreeList/DpTreeListNode.vue
- src/components/core/DpUpload/DpUploadFiles.vue
- src/components/core/form/DpCheckbox.vue
- src/components/core/form/DpDatetimePicker.vue
- src/components/core/form/DpRadio.vue
- src/components/core/form/DpSearchField.vue
- src/components/core/form/DpSelect.vue
- src/components/core/form/DpTextArea.vue
- src/components/core/form/DpTimePicker.vue
- webpack.config.js
- yarn.lock
- Generate a importable package
- don't load the Components from index. Load them from the file itself. The index didn't work out :-/ 
after merged (and main used in demosplan / new package-version), demosplan should work again.
> Fix(refs T30074): demosplan frontend and UI lib

- package.json
until we publish via npm, the prepublish hook does not fire. this can be rolled back later.
> fix: use correct hook for now

- package.json
though we need a working Dev, we can't wait to publish all the time. Therefore we need something that works on install.
> fix: Make posthook Work without publishing the Package

- src/components/core/form/DpCheckbox.vue
- Add missing E2E attr for DpCheckbox.
If you want for DpCheckbox `data-cy` attr add then this attr added for div container not for input field
> chore (refs T30597): Add missing E2E attr for DpCheckbox.

- src/directives/CleanHtml/CleanHtml.js
As we allow the target attr, we have to make sure that the link is safe. Chromium seems to add `rel="noopener"` automatically as of v88, however to also ensure correct behavior for other engines, the `rel` attr is added whenever a target is set to "_blank".
See
- https://github.com/cure53/DOMPurify/issues/317
- https://developer.chrome.com/docs/lighthouse/best-practices/external-anchors-use-rel-noopener/
> Allow target blank in v-cleanhtml

- .storybook/main.js
- .storybook/preview.js
- CHANGELOG.md
- package.json
- yarn.lock
To mitigate issues arising from Webpack 4 (Storybook builder default) being installed alongside Webpack 5 (being the build tool for demosplan-ui), Storybook is configured to use Webpack 5, too.
Along the way, Storybook is upgraded to its latest version.
See:
- https://github.com/vuejs/vue-cli/issues/5986
- https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#fixing-hoisting-issues
> Configure storybook to use Webpack 5

- package.json
- webpack.config.js
- yarn.lock
To further optimize bundling, the BundleAnalyzerPlugin is a good start. To enable it, any of the build tasks can be started with the "analyze" flag, eg:
```
yarn build --analyze
```
> Add bundle analyzer

- CHANGELOG.md
- webpack.config.js
Ticket: https://yaits.demos-deutschland.de/T30430
To not run into conflicts between es6 and es5, the tiptap modules (that export esm bundles) must be included for babel-loader. This was already the case in the demosplan-core build but got overseen when moving DpEditor into demosplan-ui.
See https://stackoverflow.com/a/51860850/6234391
> Transpile tiptap esm modules

- CHANGELOG.md
- src/components/core/form/DpRadio.vue
As was implemented for other form components previously, the label props are now passed in a single object. That way it's easier to understand what they are used for.
**Breaking**: The `label` prop expects an `object` now (previously a `string`)
> refactor(refs T29004): pass label props as object

- CHANGELOG.md
- src/components/DpCheckbox/DpCheckbox.stories.mdx
- src/components/DpCheckbox/DpCheckbox.vue
- src/components/core/DpCheckboxGroup.vue
- src/components/core/DpDataTable/DpColumnSelector.vue
- src/components/core/DpEditor/DpLinkModal.vue
- src/components/core/DpTableCardList/DpTableCardListHeader.vue
- src/components/core/index.js
- src/components/index.js
- src/index.js
Moves `DpCheckbox` to the `components` root and adds some basic documentation.
(Also, fixes a duplicated import statement)
Related tickets: https://yaits.demos-deutschland.de/T30969, https://yaits.demos-deutschland.de/T30976
> docs(refs T30969): add checkbox documentation

- src/components/DpDateRangePicker/DpDateRangePicker.vue
- src/components/DpRadio/DpRadio.vue
- src/components/DpSearchField/DpSearchField.vue
- src/components/DpSelect/DpSelect.vue
- src/components/DpSlidingPagination/DpSlidingPagination.vue
- src/components/DpTimePicker/DpTimePicker.vue
- src/lib/ActionMenu.js
- src/lib/validation/utils/assignHandlerForTrigger.js
- src/mixins/prefixClassMixin/prefixClassMixin.js
At the moment, **main** can't be build. As files have moved in both #76 and #71, resolving of conflicts was not happening as magically as it looked. This PR fixes these issues.
For the `addFormHiddenField` method, which has been moved to demosplan-core, we decided to duplicate it here (as long as "classic" forms have to be supported), because the only alternative approach that makes sense here would be to introduce some kind of hooks in the validation process, which is out of scope for dpValidate as of now.
> Fix paths after failed merge

- CHANGELOG.md
- src/components/core/DpEditor/DpEditor.vue
- src/components/core/DpEditor/libs/handleWordPaste.js
Ticket: https://yaits.demos-deutschland.de/T31024
- when copy/pasting from word, empty spaces are no longer removed
- another bug was fixed along the way (dynamically importing `EditorObscure` made it unavailable, so when testing in demosplan, the editor was not rendered)
> fix(refs T31024): keep empty spaces

- CHANGELOG.md
- package.json
- src/components/core/DpEditor/DpBoilerPlateModal.vue
It is not needed anymore, as the boilerplates store is registered in bundle entrypoints now.
Also, it caused a bug when an outer component was destroyed but remounted afterwards.
> Do not unregister boilerplates module 

- CHANGELOG.md
- src/components/core/notify/DpNotifyContainer.vue
This PR sets the correct value for `aria-live` in DpNotifyContainer when document becomes visible. The logic was mistakenly inverted before.
> Set correct value for `aria-live` in DpNotifyContainer

- CHANGELOG.md
- tokens/color.json
Some projects will require to override black and white. So here we go.
> Make white and black themeable

- src/components/core/DpTableCardList/DpTableCardListHeader.vue
- The spacing of the checkbox was a little odd so little adjustments need to be applied on css level now the table header has the exact same spacing as the table list (in user interface)
Build demosplan-ui from git commit hash:
- in package.json adjust package like this: `"@demos-europe/demosplan-ui": "github:demos-europe/demosplan-ui#f1f5f97e9df3503642a865c7defa63da913456d8"`
- run `yarn` in core to fetch this PRs demosplan-ui state
- in terminal navigate to ui like this: `cd $DEMOSPLAN_HOME/node_modules/@demos-europe/demosplan-ui`
- run `yarn; yarn prepack`
- now build project
In Interface:
- login as support user
- [navigate to /user/list](http://bobhh.dplan.local/app_dev.php/user/list)
- check if this problem:
- is now solved like this:
> bug(refs: T31449): fix checkbox positioning in user list

- package.json
- src/components/DpDatepicker/DpDatepicker.vue
The library we are using ([a11y-datepicker](https://github.com/mathislucka/a11y-datepicker/)) was iomported as es module. That didn't works with the current setup, so we just have to load the cjs module and everything is fine.
**Ticket** https://yaits.demos-deutschland.de/T31929
> fix(refs T31929): Make DpDatepicker loadable

- CHANGELOG.md
- src/components/DpTimePicker/DpTimePicker.vue
- src/components/core/DpAutocomplete.vue
- src/components/core/DpCard.vue
- src/components/core/DpEditor/DpEditor.vue
- src/components/core/DpTableCardList/DpTableCardListHeader.vue
- src/components/core/DpToggleForm.vue
Ticket: https://yaits.demos-deutschland.de/T32170
Dynamic imports are causing bugs every now and then, hence we decided is to refactor them and replace those with static imports to avoid future bugs. There is a tradeoff however since the bundle output will be slightly bigger this way but we decided it is still worth it, to adjust these imports.
> Fix(refs T32170): refactor dynamic imports

- src/components/DpPager/DpPager.vue
https://yaits.demos-deutschland.de/T31974
- the pagination selection should be before the dropdown and should not have a term between the pagination and the dropdown.
> fix(refs T32170): adjust layout of sliding dppager

- src/components/core/DpDataTable/DpColumnSelector.vue
- use localStorageKey to generate distinct Event Actions
- passing a Set as Event Name did not work, so it has to be converted to string first
> Generalize column selection tracking

- src/components/core/DpDataTable/DpSelectPageItemCount.vue
As Part of the migration to Vue3 we move all functional components to "classic" Compontents. There changed an lot and for sake of simplicity and consistancy having a template is great.
This PR moves only the render function content to the template
> chore(refs T19787, T19759): Rebuild template for selectPageItemCount

- CHANGELOG.md
- src/components/DpFlyout/DpFlyout.vue
To be able to use the expanded state of DpFlyout right within the consuming component, it must be exposed to the scoped slot.
> Expose isExpanded in scoped slot

- CHANGELOG.md
- src/components/DpMultiselect/DpMultiselect.vue
Ticket: https://yaits.demos-deutschland.de/T32855
- Add more types for prop value
- Bind props to slot, so they are available for parent
- Show selection buttons only if prop for controls is true
- Add all event listener
> bug(refs T3285): Fix multiselect

- .gitignore
- CHANGELOG.md
- src/components/core/DpDataTable/DpTableHeader.vue
Ticket: https://yaits.demos-deutschland.de/T32865
- `this` is not valid in template and causes console errors hence has been removed
- On `mounted` can be problematic when working with `$refs` since refs are filled after the component mounts. Hence, to avoid a race condition like scenario, we can simply use another lifecycle hook here. Since `beforeUpdate` was documented here https://vuejs.org/guide/essentials/lifecycle.html#lifecycle-diagram as the hook to use when data changes, this has been implemented accordingly
- updated gitignore to not track irrelevant folders anymore
> fix(refs: T32865): checkbox at wrong position and console errors

- src/components/core/DpDataTable/DpTableHeader.vue
**Ticket:** https://yaits.demos-deutschland.de/T19759
**Description:** This code defines three methods: `toggleExpandAll`, `toggleSelectAll`, and `toggleWrapAll`.
- `toggleExpandAll` emits the event 'toggle-expand-all' using $emit
- `toggleSelectAll` emits the event 'toggle-select-all' using $emit
- `toggleWrapAll`emits the event 'toggle-wrap-all' using $emit
**Important:** This PR depends on https://github.com/demos-europe/demosplan-ui/pull/230 and can only be merged after PR #230 is merged.
> Fix(T32651): Vue migration: adjust Header to work with DpDataTable template-based component

- CHANGELOG.md
- src/components/DpMultiselect/DpMultiselect.vue
Ticket: https://yaits.demos-deutschland.de/T33153
Add some missing props to wrapper component to pass to vue-multiselect. `custom-label` needs to have `undefined` as default, because otherwise we get an empty label if the parent didn't give one.
> bug(refs T33153): Add missing props for multiselect

- CHANGELOG.md
- src/components/core/DpDataTable/DpDataTable.vue
in Vue3 having a v-if on the same element as a v-for causes trouble. And this Changes should not do any harm in vue2
> Chore: Clean up and simplify tableRow condition

- CHANGELOG.md
- src/components/DpButtonRow/DpButtonRow.vue
this went unnoticed when implementing the subtle button...
> fix: empty string is invalid for "variant" prop

- tests/DpNotifyMessage.spec.js
Some classes were referenced within tests. This is fixed hereby.
> Fix tests after Tailwind update

- CHANGELOG.md
- src/components/DpMultiselect/DpMultiselect.vue
Ticket: https://yaits.demos-deutschland.de/T33411
We need to give the data-cy prop on its own, because otherwise it will be added as `dataCy` instead of `data-cy`.
> bug(refs T33411): Add prop for data-cy on its own

- CHANGELOG.md
- src/components/DpTabs/DpTabs.stories.mdx
https://yaits.demos-deutschland.de/T33323
- add storybook documentation to DpTabs.
> chore (refs T33323): add storybook documentation to DpTabs.

- CHANGELOG.md
- src/components/DpSelect/DpSelect.vue
- src/components/shared/translations.js
https://yaits.demos-deutschland.de/T31115
- add Trans-Key to translations.js
- remove Translator.trans from DpSelect.
> F t31115 remove translator from dp select

- src/index.js
For some reasons we need both. Named and default exports. This should fix the Bugs wich leaded to the role back of 1.8. 
since I ordered the entries alphabetically, the changes look more than they are.
Only the second and third block is new. The upper block is just sorted
> Fix: Add a default export to index.js

- tests/form/DpSelect.spec.js
We broke the test by changing the value of the placeholder option. Now we use the translation file to not have to duplicate strings here.
> fix: use correct translation values

- CHANGELOG.md
- buildTokens.js
- src/components/DpStickyElement/DpStickyElement.vue
- tokens/src/zIndex.json
- tokens/tokens.zIndex.stories.mdx
- adapt utility classes to Tailwind naming
- use -10/+10 for z-indexes around zero to acommodate for the fact that there will be cases where users may squeeze something in there
- shorten scss var name according to the respective Tailwind naming
> Tweak z-index var names + values

- CHANGELOG.md
- src/components/DpMultiselect/DpMultiselect.vue
- fix Validate directive in DpMultiselect.
With Storybook https://github.com/demos-europe/demosplan-ui/pull/408 there was an error with dpValidate directive.
`[Vue warn]: Failed to resolve directive: dp-validate-multiselect`
See in: https://github.com/demos-europe/demosplan-ui/pull/408#discussion_r1283999579
> chore: fix Validate directive in DpMultiselect.

- CHANGELOG.md
- src/components/DpTimePicker/DpTimePicker.vue
**Ticket:** https://yaits.demos-deutschland.de/T34111
**Description:** This PR fixes issue with the permanently opened dropdown menu. After adding Tailwind CSS and adjusting new classes, the v-show directive with the style `'display: none;'` does not win in the specificity hierarchy. As a result, it has no impact on the flyout element:
- add a `hidden` class from the Tailwind library when the showFlyout variable has a negative value.
> Fix(T34111): permanently opened dropdown

- CHANGELOG.md
- src/components/DpDateRangePicker/DpDateRangePicker.vue
- src/components/DpDatepicker/DpDatepicker.vue
https://yaits.demos-deutschland.de/T34082
https://github.com/demos-europe/demosplan-core/pull/1860
- add E2E Props.
> chore (refs T34082): add E2E Props.

- CHANGELOG.md
- src/components/DpTreeList/DpTreeList.vue
- src/lib/Stickier.js
**Ticket:** https://yaits.demos-deutschland.de/T34173
**Description:** This PR fixes the problem of text flickering when scrolling down. The problem arises when the element's container has limited space at the top and attempts to jump to the bottom. However, in this scenario, transitioning to the bottom is unnecessary, the element should be fixed at the top of the container. An extra check has been added wherever the function `_bindBottom` is called: when the value of the `stickToDirection` is 'top' the funciton `_bindBottom` will not be performed.
- when creating a new sticky object, set `'top'` as the value for `stickToDirection` in the DpTreeList component.
> Fix(T34173): flickering text when scrolling down

- src/components/DpContextualHelp/DpContextualHelp.vue
- src/components/DpDataTable/DpColumnSelector.vue
- src/components/DpDataTable/DpDataTable.vue
- src/components/DpLabel/DpLabel.vue
- src/components/DpModal/DpModal.vue
- src/components/DpMultiselect/DpMultiselect.vue
- src/components/DpSelect/DpSelect.vue
- src/components/DpTreeList/DpTreeListCheckbox.vue
- src/components/core/DpAnonymizeText.vue
- src/components/core/DpEditor/DpEditor.vue
- src/components/core/DpEditor/DpLinkModal.vue
- src/components/core/DpEditor/DpResizableImage.vue
- src/components/core/DpEditor/DpUploadModal.vue
- src/components/core/DpEditor/libs/editorCustomDelete.js
- src/components/core/DpEditor/libs/editorCustomInsert.js
- src/components/core/DpEditor/libs/editorCustomMark.js
- src/components/core/DpObscure.vue
- src/components/core/DpUpload/DpUploadedFile.vue
- src/components/core/DpUpload/utils/UppyTranslations.js
- src/components/shared/translations.js
- src/lib/validation/utils/validateInputField.js
- src/mixins/dpValidateMixin.js
- src/utils/lengthHint/lengthHint.js
- tests/DpTreeListCheckbox.spec.js
- tests/Obscure.spec.js
- tests/__snapshots__/DpContextualHelp.spec.js.snap
Ticket: https://yaits.demos-deutschland.de/T31187
- move all keys used in demosplan-ui that were previously defined in demosplan-core to `translations.js`
- remove Translator usages
> refactor(refs T31187): remove Translator usages

- CHANGELOG.md
The changelog entry was accidentally added to the most recent release, but the changes (https://github.com/demos-europe/demosplan-ui/pull/445) were not actually included in it
> refactor(refs T31187): move changelog entry

- CHANGELOG.md
After merging main into `f_dp_tooltip` after a while of doing nothing, the changelog got mixed up.
> fix: Adjust Changelog after auto-merge

- CHANGELOG.md
- src/components/DpContextualHelp/DpContextualHelp.vue
- src/components/DpTooltipIcon/DpTooltipIcon.vue
Both DpContextualHelp and DpTooltipIcon do the same.
However, as the team agreed to go with DpContextualHelp,
it is now prepared to cater for all cases DpTooltipIcon
is used in:
- defaults to the question mark icon, but supports other icons
- defaults to medium size, but supports other icon sizes
- uses DpIcon instead of fontawesome
> Consolidate tooltip components

- src/components/DpTooltipIcon/DpTooltipIcon.stories.mdx
- src/components/DpTooltipIcon/DpTooltipIcon.stories.tsx
- Migrate DpTooltipIcon stories to v7.
> chore: Migrate DpTooltipIcon stories to v7.

- .storybook/main.js
- .storybook/preview.js
- CHANGELOG.md
- package.json
- postcss.config.js
- tailwind.config.js
- yarn.lock
to further enable component development within storybook, tailwind styles are made available in storybook.
Most tutorials on this topic refer to the deprecated @storybook/addon-styling, however @storybook/addon-styling-webpack installs way less dependencies and seems to do the same job.
As we are now able to build tailwind in demosplan-core, we can remove the safelist hack that forced tw to render all css classes by default.
> feat(refs T27593): add tailwind to storybook

- .storybook/main.js
- .storybook/preview.js
the new api of addon-styling-webpack is different from the old one, so postcss must be configured more explicitly. See https://github.com/storybookjs/addon-styling-webpack/issues/1
> feat(refs T27593): use correct webpack config for tw

- src/components/DpTooltip/utils/tooltip.js
- src/directives/Tooltip/Tooltip.js
**Ticket** https://yaits.demos-deutschland.de/T34566
When using the tooltip-directive It was only supportet to pass the content. 
But we also have situations, where we pass Objects with container, content or classes. 
That was forgotten when rewriting the tooltip directive. 
So we have to reimplement it now
> fix(refs T34566): Pass propper Values to init Tooltips

- src/components/DpTooltip/utils/tooltip.js
- src/directives/Tooltip/Tooltip.js
**Ticket** https://yaits.demos-deutschland.de/T34571
to allow clicking on Buttons where the `tooltip` has been after hovering off.
300 ms should be enough for a rebounce and for normal user interaction to
not click before the tooltip has been removed.
Actually we need this tweak only in cases, where the z-index get increased from outside
with a class that defines the z-index after `z-below-zero` in the css-file
> fix(refs T34571): Shorten Delay for destroytooltip

- CHANGELOG.md
- src/components/DpContextualHelp/DpContextualHelp.vue
- src/components/DpTooltip/utils/tooltip.js
**Ticket:** https://yaits.demos-deutschland.de/T34571
**Description:** There are cases when tooltips are in the modal windows and have a smaller z-index than the modal.
- added a method that checks the z-index of the parent element and appends `zIndex + 1` to the style of the tooltip
> Fix(T34571): place tooltip in the foreground

- CHANGELOG.md
- src/components/DpTooltip/utils/tooltip.js
**Ticket:** https://yaits.demos-deutschland.de/T34571
**Description:** There are cases when tooltips are in the modal windows and have a smaller z-index than the modal.
- added a method that checks the z-index of the parent element and appends zIndex + 1 to the style of the tooltip
> Fix(T34571): place tooltip in the foreground 

- CHANGELOG.md
- src/components/DpTooltip/utils/tooltip.js
- src/directives/Tooltip/Tooltip.js
**Ticket:**  https://yaits.demos-deutschland.de/T34716
**Description:** This PR adds a method that updates the tooltip value.
> Fix(T34716): add an update method in the tooltip directory

- src/components/DpTabs/DpTabs.stories.tsx
- Fix DpTab Storybook error.
`this.tabs[0] is undefined`
> chore: Fix DpTab Storybook error.

- tests/DpContextualHelp.spec.js
- tests/__snapshots__/DpContextualHelp.spec.js.snap
**Description:** Remove the snapshot test for the `DpContextualHelp` component due to its dynamically changing `aria-describedby` value, which currently causes failures. Since we require a demosplan-ui release, it could be skipped for now and fixed later.
> snapshot test for the DpContextualHelp component

- package.json
- yarn.lock
seems to fail if using dependabot PR
> chore: bump @vue/eslint-config-typescript to 12

- .github/dependabot.yml
All tiptap (and storybook) dependencies will have to be updated at once, otherwise things will break. So here we go.
> feat: group tiptap and storybook dependabot PRs

- CHANGELOG.md
- tests/form/DpCheckbox.spec.js
- tests/form/DpInput.spec.js
- tests/form/DpSelect.spec.js
- tests/form/shared/Label.js
Ticket: https://yaits.demos-deutschland.de/T29004
- the label tests (that were disabled after refactoring the label props to be a single object) are fixed and enabled again
- some more tests that were disabled in DpInput.spec.js for unknown reasons are enabled again as well
Run the tests, there should be no error
> refactor(refs T29004): re-add label tests

- .github/dependabot.yml
- CHANGELOG.md
- package.json
- yarn.lock
As the peer dependency needs to be in sync with vue-template-compiler bc jest tests throw an error otherwise, and bc demosplan-core has bumped vue to 2.7.15 as well, we can bump both to 2.7.15 here, as well.
Closes #608.
> chore: bump vue and vue-template-compiler to 2.7.15

- CHANGELOG.md
- src/lib/Stickier.js
Ticket: https://yaits.demos-deutschland.de/T34956
If the element ends below context the position should be the bottom of context. Otherwise the element has not enough space and is not reachable. Don't stick to direction in this case. 
It seems like the bug was introduced with this fix https://github.com/demos-europe/demosplan-ui/pull/438
Since this doesn't fix the bug completely (see https://yaits.demos-deutschland.de/T34173) I suggest to revert it and to try to fix it another way.
> bug(refs T34956): Fix stickier position

- CHANGELOG.md
- src/components/DpModal/DpModal.vue
**Ticket:** https://yaits.demos-deutschland.de/T33788
**Description:** This PR addresses the issue where scrolling becomes impossible after closing the modal window:
- call the `preventScroll` function in the `toggle() `method for cases where the `@after-leave` transition does not work correctly, especially when there is a parent component (such as a specialized modal like AssignEntityModal, ConsolidateModal or CopyStatementModal)
> Fix(T33788): disabled scrolling after closing the modal window

- CHANGELOG.md
- src/lib/validation/utils/assignHandlerForTrigger.js
- src/mixins/dpValidateMixin.js
**Ticket:** https://yaits.demos-deutschland.de/T33137 --> 1.PLZ wird 2x angezeigt (nur beim Feld PLZ tritt der Fehler auf
**Description:** This PR fixes the issue with incorrect field names in the error message: [object Set] 
JavaScript `Set` was used for storing a collection of unique fields. However it does not work correctly after installing a new version of demosplan-ui in demosplan core.. 
- use filter() function to display only unique fields
> Fix(T33788): display only unique fields in the error message

- .storybook/main.js
- CHANGELOG.md
- package.json
- yarn.lock
- remove @storybook/addon-mdx-gfm which was only needed when migrating from storybook 6
- remove special jackspeak resolution as we found the fix for the "string-width error" (running `yarn upgrade jest`)
- define engines for npm and node to keep demosplan-ui in sync with demosplan-core
> Cleanup package.json

- src/components/DpAccordion/DpAccordion.vue
If the text doesn't fit in one line, the text is aligned center and it does not match the other buttons.
> bug: Align text for accordion button left

- src/components/DpBadge/DpBadge.vue
As we're already using the `rounded...` classes (and in preparation of removing legacy utility css), let's use Tailwind class instead of demosplan-core class here.
> chore: use Tailwind class instead of demosplan-core class

- CHANGELOG.md
- package.json
- yarn.lock
There are too many dependencies and transitive uses of string-width and
strip-ansi in differing versions. This resolves the tree so that our
current jest and webpack setups are able to run
The ChatGPT-aided fix was to manually upgrade string-width after
adding the version requested by jest to our devDependencies.
> Repair jest build

- CHANGELOG.md
- src/components/DpEditor/DpLinkModal.vue
- src/components/DpEditor/DpUploadModal.vue
Since the imports can't be resolved directly from `~/components` atm. The Modals are broken.
Simple fix is to change the imports, like i did here. In a second step, we have to fix the setup, that we can use the imports the way we want to.
> fix(refs T35888): Adjust broken imports

- CHANGELOG.md
- src/components/DpAccordion/DpAccordion.vue
- src/components/DpDataTableExtended/DpSelectPageItemCount.vue
- src/components/DpDatepicker/DpDatepicker.vue
- src/components/DpDetails/DpDetails.vue
- src/components/DpEditor/DpUploadModal.vue
- src/components/DpSearchField/DpSearchField.vue
- src/components/DpTextArea/DpTextArea.vue
- src/components/DpTimePicker/DpTimePicker.vue
- src/components/DpTreeList/DpTreeListNode.vue
To be able to drop "height" and "width" custom utilities, we have to use the appropriate tailwind classes.
> Use tailwind utility classes for height and width

- CHANGELOG.md
- src/lib/DpApi.js
Ticket: https://yaits.demos-deutschland.de/T35953
If you stringify a form data object you get an empty object. For form post we need to send the form data as it is.
> bug (refs T35953): Don't stringify form data

- CHANGELOG.md
- src/lib/DpApi.js
Whether it is required by spec is debated, especially when it comes to http2, but as the vuex-json-api plugin also sends headers in the format of "First-Char-Uppercase", this is done here, too, for the time being.
> Send uppercase request headers in DpApi

- CHANGELOG.md
- src/lib/DpApi.js
- This PR is the front-end part of enabling x-csrf-token as header which was mainly introduced to prevent the purple error messages about missing csrf tokens when loading addons on various areas of dplan
https://github.com/demos-europe/demosplan-core/pull/2586
Before removing the hidden input field throughout dplan this PR needs to be merged first and a new release is needed
> chore: send csrf token when submitting a rpc2.0 call

- CHANGELOG.md
- src/components/DpEditor/DpLinkModal.vue
Adds the possibility to add `mailto` links via the link modal of DpEditor.
> feat: allow mailto links in editor

- .gitignore
- CHANGELOG.md
- package.json
As we do not need it here (Storybook consumes the index.css directly), and also do not need it in projects using demosplan-ui (as they import the tailwind.config and tokens, rather than a compiled file), we can remove the compile step here.
> chore: remove "build:css" script

- CHANGELOG.md
- src/components/DpMultiselect/DpMultiselect.vue
- src/components/DpSelect/DpSelect.vue
**Ticket:** https://yaits.demos-deutschland.de/T36635
**Description:** To improve the UX and provide information about invalid fields, add the prop called `dataDpValidateErrorFieldname`. This prop is needed for the `dpValidate` mixin to display the correct error message with the invalid fields.
[PR in Core](https://github.com/demos-europe/demosplan-core/pull/2853)
> Fix(T36635): improve error validation for DpMultiselect and DpSelect components

- CHANGELOG.md
- src/lib/DpApi.js
When moving from axios to fetch, it was overlooked that axios serializes params by default, and we only do that occasionally. This leads to the params being dropped in the fetch request whenever "serialize: true" is set via the options arg.
To overcome this, and as we always need to serialize params within get requests, the request params are always appended as stringified value to the url. As the "url" argument may already have params appended, this needs to be handled as well.
The "payload" variable has been renamed into "fetchOptions" to level up readability while distinguishing it from the "options" variable still being used in dpApi.
Also, "options" and "params" has been removed from the request payload as the fetch method does not use these values.
See …
> Always serialize request params for GET request in dpApi

- CHANGELOG.md
- src/components/DpUploadFiles/utils/GetFileIdsByHash.js
- src/lib/DpApi.js
This tackles some leftovers from the axios removal. While options were passed into axios by default before, we do not use it anymore - it was only used to indicate serialization of params which is done by default for get requests now.
- remove "serialize: true" from get route in getFileIdsByHash as params are now always serialized
- properties within the object passed to doRequest as param are reordered to match the most common way of ordering them when calling dpApi() directly in demosplan-core: method first, then url
- add 'headers' property in the object passed to doRequest as param directly instead of wrapping it in params. however this is only used when calling dpApi() directly, as the alias calls like dpApi.post() are used by API2.0 routes which are equipped with api2defaultHeaders …
> Cleanup dpApi

- CHANGELOG.md
- src/components/DpDataTable/DpDataTable.vue
- src/components/DpDataTable/DpResizableColumn.vue
- src/components/DpDataTable/DpTableHeader.vue
- src/components/DpUploadFiles/DpUploadFiles.vue
- src/mixins/index.js
- src/mixins/sessionStorageMixin.js
**Ticket:** [DPLAN-11462](https://demoseurope.youtrack.cloud/issue/DPLAN-11462/macht-spalten-in-der-Abschnittsliste-resizable)
**Description:** This PR adds functionality to save the width of the columns to session storage, eliminating the need to adjust the width every time the user reopens the page. Additionally, it fixes some problems with the `is-resizable` feature.
It saves in the sessionStorage with the key `dpDataTable:data-col-field=${field}`
[PR in Core](https://github.com/demos-europe/demosplan-core/pull/3003)
> Feat(dplan-11462): DataTable: save width to the session storage

- CHANGELOG.md
- src/shared/props/props.js
As the "length" variable is assigned to "maxlength" prop, without calling it, it does not need to be a function, rather an object.
> Make length prop validation work

- CHANGELOG.md
- src/components/DpDateRangePicker/DpDateRangePicker.vue
- src/components/DpDatepicker/DpDatepicker.vue
- src/lib/validation/utils/helpers.js
- src/lib/validation/utils/validateDatepicker.js
**Ticket:** [DPLAN-1965](https://demoseurope.youtrack.cloud/issue/DPLAN-1965/Invalid-Inputs-beim-Verfahrenerstellen-werfen-nicht-die-richtigen-Fehlernachrichten) 
**Description:**  This PR adjusts the validation of the Datepicker.
- add the `data-dp-validate-error-fieldname` attribute to the Datepicker via `setAttribute() `to facilitate the display of the field name in case of an error.
- include `name` attributes `r_startdate` and `r_enddate` in the validation form, as the date field need to be validated every time the value changes and not only if the field has an `required` attribute
- an empty string is accepted if the `required` attribute is not present.
[PR in Core](https://github.com/demos-europe/demosplan-core/pull/3038)
> Fix(dplan 1965): improve error validation of the Datepicker

- CHANGELOG.md
- src/components/DpDataTable/DpDataTable.vue
- src/components/DpDataTable/DpResizableColumn.vue
I removed the behavior in DpDataTable, that on resize the followed Column gets resized too. Now all following cols get "pushed away".
I don't know what GitHub/my IDE did, but I only changed DpResizeableColumn. DpDataTable should only be autolinted.
**Ticket** https://demoseurope.youtrack.cloud/issue/DPLAN-11529/Abschnittstabelle-Nach-Breite-verkleinern-einer-Spalte-wird-die-Spalte-rechts-daneben-sehr-breit-gezogen
> fix(refs DPLAN-11529): Don't change Width from Next El on Datatable resize

- CHANGELOG.md
- src/components/DpLabel/DpLabel.vue
**Ticket:** [DPLAN-3297](https://demoseurope.youtrack.cloud/issue/DPLAN-3297/2-Als-Fachplanung-mochte-ich-Institutionen-per-E-Mail-zu-einem-Verfahren-einladen-konnen-obwohl-sie-noch-nicht-in-BLP)
**Description:** DpLabel: use the DpContextualHelp component instead of the tooltip directive and place it near the label.
> fix(DPLAN-3297): DpLabel: adjust tooltip

- CHANGELOG.md
- src/components/DpCheckboxGroup/DpCheckboxGroup.vue
**Ticket:** [DPLAN-11483](https://demoseurope.youtrack.cloud/issue/DPLAN-11483/8-2-Als-Planungsburo-brauche-ich-eine-Admin-Rolle-um-Verfahren-selbst-anlegen-und-durchfuhren-zu-konnen) 
**Description:** Fix the warning: _Type check failed for the prop 'dataCy'_, bacause it expected a string but received a boolean. Change it to `null`, as this attribute does not appear in the element if it is null.
> fix(DPLAN-11483): vue warning on type check

- CHANGELOG.md
- src/lib/validation/utils/assignHandlersForInputs.js
- src/lib/validation/utils/helpers.js
- tailwind.config.js
**Ticket:** [DPLAN-2231](https://demoseurope.youtrack.cloud/issue/DPLAN-2231/Fehlermeldung-das-Verfahren-nicht-verortet-ist-in-jeden-Assistent-schritt-angezeigt)
**Description:** This PR fixes an issue with validation when a 'data-dp-validate-if' attribute is provided in an input within a fieldset instead of directly within a form, because the query selector (line 20) should search the entire form rather than just the fieldset; otherwise, it returns null.
- check if a `fieldset` is provided instead of a `form` when using `input.closest('[data-dp-validate]')`
- cognitive complexity has been reduced for the 'assignHandlersForSingleInput' method to address a SonarCloud issue
> fix(DPLAN-2231): fix 'data-dp-validate-if' within a fieldset

- CHANGELOG.md
- package.json
- src/components/DpTooltip/utils/tooltip.js
It was the idea to hide the tooltip on mouseleave and only destroy it after 300ms to prevent recreating it again and again. But it turned out that it then sometimes got created twice. That had the effect, that the second tooltip didn't disappear.
**Ticket** DPLAN-1898
> fix(refs DPLAN-1898): Destroy Tooltip instead of hiding

- CHANGELOG.md
- src/components/DpDatepicker/DpDatepicker.vue
Ticket: [DPLAN-11472](https://demoseurope.youtrack.cloud/issue/DPLAN-11472)
Only set attribute if datePickerInput is defined
> bug (refs DPLAN-11472): Only setAttribute if datePickerInput is defined

- CHANGELOG.md
- src/lib/DpApi.js
Ticket: [DPLAN-11586](https://demoseurope.youtrack.cloud/issue/DPLAN-11586/Stellungnahme-als-Entwurf-speichern-spater-nicht-sichtbar-unter-Meine-Entwurfe)
If you're sending form data using FormData, you should not manually set the Content-Type header. The browser will automatically set it to multipart/form-data and append the necessary boundary parameter.
> bug (refs DPLAN-11586): Remove header from form posts

- CHANGELOG.md
- src/utils/index.js
- src/utils/resistFingerprintingDuckTest.js
As we might need this in several contexts, it is added in demosplan-ui.
Related tickets: 
- https://demoseurope.youtrack.cloud/issue/ProdArchiv-66/Klick-auf-Karte-wahlt-Plane-aus-die-nicht-auf-dem-Punkt-liegen-Firefox
- https://demoseurope.youtrack.cloud/issue/DPLAN-11647/Klick-Problem-auf-der-Seite-Importierte-Stellungnahmen-uberprufen-Schulung
> feat: add resistFingerprintingDuckTest

- CHANGELOG.md
- src/components/DpDataTable/DpDataTable.vue
- src/components/DpDataTableExtended/DpDataTableExtended.vue
In dpDataTable:
If the feature "lock item" (`lockCheckboxBy`) is on, these items shouldn't be selected when using select all.
> fix: Select All should only select selectable items

- CHANGELOG.md
- src/components/DpMultistepNav/DpMultistepNav.vue
https://demoseurope.youtrack.cloud/issue/DPLAN-11668/Hooks-Public-View-Hooks
- Add missing Hooks/Selectors for DpMultistepNav.
> chore (refs DPLAN-11668): Add missing Hooks for E-2-E Test.

- CHANGELOG.md
- src/components/DpInput/DpInput.vue
Ticket: https://demoseurope.youtrack.cloud/issue/DPLAN-2759
Sometimes we don't want a label visually, but there should be one nonetheless for accessibility reasons.
Related PR
https://github.com/demos-europe/demosplan-core/pull/3235
> bug(refs DPLAN-1879): Add hidden attribute for label

- CHANGELOG.md
- src/components/DpInput/DpInput.vue
- src/components/DpLabel/DpLabel.vue
Ticket: https://demoseurope.youtrack.cloud/issue/DPLAN-2759
Hidden prop should rather be handled directly in DpLabel instead of DpInput. 
Related PR
https://github.com/demos-europe/demosplan-ui/pull/892
> bug(refs DPLAN-1879): Move hidden prop to DpLabel

- CHANGELOG.md
- src/components/DpDataTable/DpDataTable.vue
Ticket: https://demoseurope.youtrack.cloud/issue/DPLAN-2071/Text-fehlt-wenn-die-Verfahrenssuche-ein-enthalt
Escape whitspaces and `+` for searching the table.
> bug(refs DPLAN-2071): Escape special characters for searching

- CHANGELOG.md
- src/components/DpButton/DpButton.vue
- src/components/DpButtonIcon/DpButtonIcon.vue
- src/components/DpDataTable/DpDataTable.vue
- src/components/DpEditableList/DpEditableList.stories.mdx
- src/components/DpEditableList/DpEditableList.stories.tsx
- src/components/DpSplitButton/DpSplitButton.vue
- src/components/DpTreeList/DpTreeListCheckbox.vue
- src/components/DpUploadFiles/DpUploadFiles.vue
Refactor: Use tailwind class for hiding visually instead of custom class. 
Related PR https://github.com/demos-europe/demosplan-core/pull/3249
> refactor: Use tailwind class for hiding visually

- CHANGELOG.md
- tailwind.config.js
As this setting may be added when extending tailwind.config.js from other projects, this does not need to be set here.
See https://github.com/demos-europe/demosplan-core/pull/3272 for reasoning about this change.
> Remove !important tailwind config

- CHANGELOG.md
- src/components/DpEditor/DpEditor.vue
https://demoseurope.youtrack.cloud/issue/DPLAN-1952/Tiptap-Shortcut-Strg-v-fugt-nicht-den-Text-ein-welcher-zuvor-mit-dem-Ausschneiden-Button-entfernt-wurde
- Fix cut methode for TipTap Editor.
- execCommand command is no longer recommended, some browsers don't support it.
- getSelection method itself does not inherently copy or move the selected text to the system clipboard directly.
>  fix (refs DPLAN-1952): Fix cut methode for TipTap Editor.

- .npmignore
- babel-jest-transformer.js
There is no need to include the tests in the published package of this library. They are now excluded. Additionally, a file that used to be part of the build stack was removed. The build behaviour and tests do not change at all with or without that file and it is referenced nowhere.
> Reduce package size

- tests/Obscure.spec.js
- tests/components/DpTreeList/DpTreeList.spec.js
- tests/components/DpTreeList/DpTreeListNode.spec.js
https://demoseurope.youtrack.cloud/issue/DPLAN-11885/Unit-Tests-schreiben
https://demoseurope.youtrack.cloud/issue/DPLAN-23/vue-test-utils-von-v1-auf-v2-upgraden
https://test-utils.vuejs.org/migration/
- Upgrade Jest setup to work with vue3 compat mode.
- destroy is now unmount to match Vue 3.
- propsData is now props.
- No more createLocalVue.
> F dplan 11885 upgrade jest test vue3

- CHANGELOG.md
- tokens/src/color/color.ui-tailwind.json
As yellow-dark-1 feels to dirty to be used on larger areas but charts need color, not background prop (and we can's use bg-status-[changed|progress|complete] for this reason), another token group is introduced which duplicates
text-status-[changed|progress|complete]-icon but uses yellow-base instead of yellow-dark-1.
> feat: add fill color token

- README.md
- docker-compose.local.yml
- package.json
To overcome the uncertainty of different node versions for local development, a docker container is used.
The container can be started and shelled into with `yarn c:dev`.
> feat: add a docker setup for local development

- CHANGELOG.md
- src/components/DpEditor/DpEditor.vue
- src/components/DpEditor/libs/editorCustomMark.js
- src/components/DpEditor/libs/editorObscure.js
**Ticket** 
[DPLAN-12305](https://demoseurope.youtrack.cloud/issue/DPLAN-12305/Munchen-Cursor-springt-nach-Korrektur-an-Ende-von-Stellungnahmetext-LHM-Ticket-INC0438291)
If there was an obscured Tag in the text, the cursor jumped to the End of the text on edit. This was caused by an unnecessarily often triggered method which checked transformed these obscured tags to a proper format.
> fix(refs dplan-12305): Prevent Cursor from jumping to End of file

- CHANGELOG.md
- src/components/DpVideoPlayer/DpVideoPlayer.vue
Ticket: [DPLAN-3428](https://demoseurope.youtrack.cloud/issue/DPLAN-3428)
Extend video player so it can also use embedded videos like from YouTube.
> feat (refs DPLAN-3428 AB#4195): Extend video player for embedded videos

- CHANGELOG.md
- scripts/utils/transformTokens.js
We cannot use Css variables within media queries. As we do not need to override breakpoints anyway, at least for now, the primitive px value is taken instead.
The change leads to the file `tokens/dist/tailwind/breakpoints.js` looking like this:
```js
module.exports = {
"sm": "620px",
"md": "904px",
"lg": "1200px",
"xl": "1400px"
};
```
instead of this:
```js
module.exports = {
"sm": "var(--dp-breakpoints-sm, 620px)",
"md": "var(--dp-breakpoints-md, 904px)",
"lg": "var(--dp-breakpoints-lg, 1200px)",
"xl": "var(--dp-breakpoints-xl, 1400px)"
};
```
> Fix token build breakpoints

- CHANGELOG.md
- scripts/utils/transformTokens.js
This fix is also applied to the 0.3.x branch in #1011 
We cannot use Css variables within media queries. As we do not need to override breakpoints anyway, at least for now, the primitive px value is taken instead.
The change leads to the file `tokens/dist/tailwind/breakpoints.js` looking like this:
```js
module.exports = {
"sm": "620px",
"md": "904px",
"lg": "1200px",
"xl": "1400px"
};
```
instead of this:
```js
module.exports = {
"sm": "var(--dp-breakpoints-sm, 620px)",
"md": "var(--dp-breakpoints-md, 904px)",
"lg": "var(--dp-breakpoints-lg, 1200px)",
"xl": "var(--dp-breakpoints-xl, 1400px)"
};
```
> Fix token build breakpoints 

- CHANGELOG.md
- src/components/DpEditor/DpEditor.vue
**Ticket:** [DPLAN-12442](https://demoseurope.youtrack.cloud/issue/DPLAN-12442/Barrierefreiheit-nicht-moglich-um-in-Stellungnahme-Textfeld-zu-schreiben-mit-der-Hilfe-von-Screen-reader)
**Description:** This PR makes the EditorContent accessible to the screen readers by adding the `role` attribute.
> B(Dplan-12442): dp editor improvement for the screenreader

- CHANGELOG.md
- src/components/DpEditor/DpEditor.vue
**Ticket:** [DPLAN-12442](https://demoseurope.youtrack.cloud/issue/DPLAN-12442/Barrierefreiheit-nicht-moglich-um-in-Stellungnahme-Textfeld-zu-schreiben-mit-der-Hilfe-von-Screen-reader)
**Description:** This PR makes the EditorContent accessible to the screen readers by adding the `role` attribute.
> Fix(Dplan-12442): dp editor improvement for the screenreader

- CHANGELOG.md
- src/components/DpEditor/DpEditor.vue
**Ticket:** [DPLAN-12449](https://demoseurope.youtrack.cloud/issue/DPLAN-12449/Geschwarzte-Stellungnahme-Text-ist-sichtbar-in-Offentlichkeit-Ansicht)
**Description:** This PR fixes an issue where the `<dp-obscure>` tag was not being applied because the `transformObscureTag` function was not triggered. This function should be executed with every update action, otherwise, the `<dp-obscure>` tag will not be transformed as expected.
However, executing it with every update action causes another bug, [DPLAN-12305 Prevent Cursor from Jumping to End of File](https://github.com/demos-europe/demosplan-ui/pull/995). To resolve this, the transformed text should be pass outside the `input` event to avoid updating the `fullText` directly. 
I think it's because `fullText` is a `v-model` of the editor, …
> fix(Dplan-12449): dp-obscure tag not being applied

- CHANGELOG.md
- src/components/DpVideoPlayer/DpVideoPlayer.vue
Ticket: [DPLAN-3428](https://demoseurope.youtrack.cloud/issue/DPLAN-3428)
Extend video player so it can also use embedded videos like from YouTube. This feature was already approved for v0.3.x, see link below. 
Related PR
https://github.com/demos-europe/demosplan-ui/pull/1005
> feat (refs DPLAN-3428 AB#4195): Enable embedded videos

- CHANGELOG.md
- src/components/DpModal/DpModal.vue
**Ticket:** https://demoseurope.youtrack.cloud/issue/DPLAN-12516/Unnotiger-Leerraum-im-Stellungnahme-Fenster
It seems that at some point, we had a slot for the close button in the modal (it is used in the statement modal in demosplan), but somehow it got lost. It is hereby restored. :sparkles:
> fix(refs DPLAN-12516): restore closeButton slot

- CHANGELOG.md
- src/components/DpEditor/DpEditor.vue
- src/components/DpEditor/libs/handleWordPaste.js
- src/components/shared/translations.js
**Ticket** [DPLAN-12602](https://demoseurope.youtrack.cloud/issue/DPLAN-12602/BLP-STN-Formular-es-wird-nicht-der-ganze-Inhalt-bei-Copy-Paste-aus-Word-ubernommen)
Since its really complicated to fetch all edgecases from msOffice Word "html", there now is an option to "protect" the editor by denying the html-input from word.
Additionally I optimized the regex a bit to be not so greedy and to better find breaks like \n or \r
> fix(refs dplan-12602): Allow DpEditor to dismiss HTML from Word

- CHANGELOG.md
- src/components/DpEditor/DpEditor.vue
- src/components/DpEditor/libs/handleWordPaste.js
- src/components/shared/translations.js
- domesticate greedy regex in ms-office parser
- Add alert to dismiss pasted html from Word (as editor flag)
This a cherry-pic from https://github.com/demos-europe/demosplan-ui/pull/1043
> fix(refs dplan-12602): Allow DpEditor to dismiss HTML from Word (#1043)

- CHANGELOG.md
- src/components/DpSelect/DpSelect.vue
Description: This PR includes an additional type for the prop `selected`, since it can be a number. (like `organisation.paperCopy` in the `PaperCopyPreferences.vue` component)
[PR in Core
](https://github.com/demos-europe/demosplan-core/pull/3810)
> refac: checkbox: add additional type to selected prop

- CHANGELOG.md
- src/components/DpDataTable/DpDataTable.vue
- src/components/DpDataTableExtended/DpDataTableExtended.vue
coming from DpDataTableExtended, the whole row-item should be available in slots, not the headerfield informations.
> fix(refs dplan-12315): Pass Item to dataTable instead of header-fields.

- CHANGELOG.md
- src/components/DpMultiselect/DpMultiselect.vue
- src/lib/validation/dpValidateMultiselectDirective.js
our validator targeted the wrong element for vue-muliselect in vue3
> fix(refs dplan-12315): Make multiselect validation vue3 compatible

- CHANGELOG.md
- src/components/DpButtonRow/DpButtonRow.vue
**Ticket:** [DPLAN-3217](https://demoseurope.youtrack.cloud/issue/DPLAN-3217/ADO-Issue-15115-Integration-EWM-Part-2-Stellungnahmedetailansicht-aus-EWM-und-dplan-vereinen)
When `disabled` is set to true, not only the primary button, but also the secondary button should be disabled.
> feat(refs DPLAN-3217): allow disabling secondary button

- CHANGELOG.md
- src/components/DpEditableList/DpEditableList.vue
- src/components/DpInput/DpInput.vue
[DPLAN-3217](https://demoseurope.youtrack.cloud/issue/DPLAN-3217)
- DpInput: Also allow numbers as values
- DpEditableList: Use DpButton instead of button and use new phosphor icons instead of fontawesome
https://github.com/demos-europe/demosplan-core/pull/3896
> feat (refs DPLAN-3217 AB#12115): Allow numbers as value for input

- CHANGELOG.md
- src/components/DpLabel/DpLabel.vue
**Ticket:** [DPLAN-12808](https://demoseurope.youtrack.cloud/issue/DPLAN-12808/Button-verschoben-Einreichende-suchen)
This PR ensures that the label is hidden if we pass `hide="true"` to `DpLabel`.
Before, with the nullish coalescing operator, 'sr-only' was only applied if `hide` was `undefined` or `null`, which was not the desired behavior.
Instead we want to apply the 'sr-only' class if `hide` is `true`, so we are now using a ternary operator instead.
> fix(refs DPLAN-12808): make sure 'sr-only' is applied if hide is true [vue 2]

- CHANGELOG.md
- src/components/DpContextualHelp/DpContextualHelp.vue
Ticket: [DPLAN-12746](https://demoseurope.youtrack.cloud/issue/DPLAN-12746/Hinzufugen-von-Textbaustein-zu-Mitteilung-Invalid-Prop)
- in order to pass tooltip options to v-tooltip in `DpContextualHelp`, we can now use the `tooltipOptions` prop; in that case, we need to include the tooltip text via the `tooltipOptions` 'content' property instead of using the `text` prop
- for all available options see https://floating-vue.starpad.dev/api/#directive-options (Note that the `classes` option has been renamed to`popperClass` in the vue 3 version (see https://floating-vue.starpad.dev/migration/migration-from-v2#directive, "Renamed props")
- if we don't want to pass options, we can keep using the `text` prop as before
- since the `text` prop can no longer be required, an error is displayed in the …
> fix(refs DPLAN-12746): allow passing options to v-tooltip [vue 3]

- CHANGELOG.md
- src/components/DpButton/DpButton.vue
**Ticket:** [DPLAN-12823](https://demoseurope.youtrack.cloud/issue/DPLAN-12823)
This PR adds 'reset' to the possible values for the `type` prop in DpButton. This allows us to use DpButton as a reset button in a form.
> fix(refs DPLAN-12823): Add 'reset' type to DpButton [vue 3]

- .yarnrc.yml
- CHANGELOG.md
Since we're running the tests in the build command, we need node_modules to be available; otherwise we get the error 
```
Module <rootdir>/node_modules/babel-jest in the transform option was not found.
```
> build: add .yarnrc.yml file

- CHANGELOG.md
- src/components/DpEditor/DpUploadModal.vue
- src/components/DpUploadFiles/DpUploadFiles.stories.mdx
- tests/DpUpload/DpUploadFiles.spec.js
**Ticket:** [DPLAN-12907](https://demoseurope.youtrack.cloud/issue/DPLAN-12907/Bild-einfugen-nicht-moglich-Erwiderung-verfassen)
When adjusting the exports in DpUploadFiles/index.ts in https://github.com/demos-europe/demosplan-ui/pull/1081, adjusting some of the imports from that file was forgotten. The imports are fixed in this PR.
Also, a minor styling adjustment was made to make spacing in the DpUploadModal more consistent.
> fix(refs DPLAN-12907): fix imports

- CHANGELOG.md
- src/components/DpDataTable/DpTableRow.vue
https://demoseurope.youtrack.cloud/issue/DPLAN-12886/Abschnitte-Tabelle-Wenn-alle-Spalten-gewahlt-sind-Ellipsis-lauft-uber-den-Schritt-Text
This PR adds some small css adjustments to the `dp-table-row` component of `dp-data-table` and aims to prevent the flyout trigger button to be overlapped by a column when re-adjusting the size of the column.
Vue3 PR: https://github.com/demos-europe/demosplan-ui/pull/1093
> fix(refs DPLAN-12886): fix overlapping flyout by adjusting css [VUE2]

- CHANGELOG.md
- src/components/DpDataTable/DpTableRow.vue
https://demoseurope.youtrack.cloud/issue/DPLAN-12886/Abschnitte-Tabelle-Wenn-alle-Spalten-gewahlt-sind-Ellipsis-lauft-uber-den-Schritt-Text
This PR adds some small css adjustments to the `dp-table-row` component of `dp-data-table` and aims to prevent the flyout trigger button to be overlapped by a column when re-adjusting the size of the column.
Vue2 PR: https://github.com/demos-europe/demosplan-ui/pull/1094
> fix(refs DPLAN-12886): fix overlapping flyout by adjusting css [VUE3]

- CHANGELOG.md
- src/components/DpTreeList/DpTreeList.vue
- src/components/DpTreeList/DpTreeListNode.vue
- src/components/DpTreeList/DpTreeListToggle.vue
- src/components/shared/translations.js
Ticket: [DPLAN-12914](https://demoseurope.youtrack.cloud/issue/DPLAN-12914/ADO-Issue-17874-zentrale-mandantenweite-Schlagwort-Verwaltung-fur-alle-registrierten-Institutionen)
- `DpTreeListNode`: allow centering the toggles for branches ('top' remains the default)
- `DpTreeListNode`: display tooltips for toggles, fix tooltip for disabled toggles
- `DpTreelistToggle`: fix label (`[object object]` was displayed in some cases), now used as tooltip
> feat(refs DPLAN-12914, #AB17874): adjust toggle alignment, display tooltips

- CHANGELOG.md
- src/components/DpEditor/DpUploadModal.vue
- src/components/DpUploadFiles/DpUploadFiles.stories.mdx
- tests/DpUpload/DpUploadFiles.spec.js
**Ticket:** [DPLAN-12907](https://demoseurope.youtrack.cloud/issue/DPLAN-12907/Bild-einfugen-nicht-moglich-Erwiderung-verfassen)
When adjusting the exports in DpUploadFiles/index.ts in https://github.com/demos-europe/demosplan-ui/pull/1082, adjusting some of the imports from that file was forgotten. The imports are fixed in this PR.
Also, a minor styling adjustment was made to make spacing in the DpUploadModal more consistent.
> fix(refs DPLAN-12907): fix DpUploadFiles imports [vue 3]

- src/components/DpDataTable/DpTableRow.vue
https://demoseurope.youtrack.cloud/issue/DPLAN-12460/Bei-Abschnittsliste-mit-wenigen-Eintragen-sind-nach-Klick-auf-drei-Punkte-die-Optionen-abgeschnitten
- the hidden and visible overflow styles were swapped by accident ... sorry, this should fix the issue now (hopefully but I double tested this now and this should do the trick finally)
> fix(refs DPLAN-12460): addjust style to always display flyout properly

- CHANGELOG.md
- docker-compose.local.yml
- package.json
> chore: bump min node to 20.18.1

- CHANGELOG.md
- tests/DpContextualHelp.spec.js
- tests/__mocks__/@phosphor-icons/vue.js
- tests/components/DpTreeList/DpTreeListNode.spec.js
- tests/form/DpInput.spec.js
- tests/form/shared/Attributes.js
This PR fixes the tests for demosplan-ui [vue3] but I needed to skip some tests for `DpInput` and `DpTreeListNode`.
Mainly because `DpTreeListNode` still contains some vue2 logic and instead of fixing the tests we should update this component and remove the `$root.$on ` occurrences.
To resolve the icon issues, we simply could add them as mocks to the __mocks__ folder with the folder structure and naming provided with this PR.
However the main goal of this PR is to have a clean test run so I think we can skip these tests for now (even though I do not like the idea) but nevertheless, we need a new release of demosplan-ui for several bugfixes for deployments hence I think we can do this for now.
> Chore fix demosplan UI tests [vue3]

- CHANGELOG.md
- src/components/DpDataTable/DpDataTable.vue
- src/components/DpDataTable/DpTableRow.vue
Ticket: https://demoseurope.youtrack.cloud/issue/DPLAN-12967/ADO-Issue-21834-Admin-Institutionsliste-Institutionen-konnen-verschlagwortet-werden
Some fixes for DpDataTable:
- Added a check to verify firstChild is an element node (nodeType === 1) before accessing its style property to prevent errors when firstChild is a text node (nodeType === 3).
- Remove overflow hidden from normal table rows, because with overflow hidden content in the table row eg selects are not shown correctly anymore. Overflow hidden was introduced to fix this [ticket](https://demoseurope.youtrack.cloud/issue/DPLAN-12886/Abschnitte-Tabelle-Wenn-alle-Spalten-gewahlt-sind-Ellipsis-lauft-uber-den-Schritt-Text), but imo it is not necessary, because the columns are resizable and the user can easily adjust the column to …
> feat(refs DPLAN-12967): fix table

- CHANGELOG.md
- src/components/DpDataTable/DpResizableColumn.vue
- src/components/DpDataTable/DpTableHeader.vue
- src/components/DpDataTable/DpTableRow.vue
Ticket: https://demoseurope.youtrack.cloud/issue/DPLAN-13085/Institutionen-gruppieren-Toggle-fur-Spalte-geht-uber-den-Kategorie-Text
- Add break words to table columns to avoid overlapping content with resizable columns.
- Make header truncatable
> bug(refs DPLAN-13085): Add break words to table

- CHANGELOG.md
- src/components/DpTreeList/DpTreeList.vue
- src/components/DpTreeList/DpTreeListNode.vue
Within DpTreeList: If you want to drop a draggable element in an empty category, its not possible since there is no space to drop it into. Therefor I added a spacer for that case.
> chore: Add drop space for DpTreeList

- CHANGELOG.md
- src/components/DpFlyout/DpFlyout.vue
Ticket https://demoseurope.youtrack.cloud/issue/DPLAN-12969
A prop `variant` is added to `DpFlyout`. It can be set to `'dark'` to set a darker background-color for the flyout trigger. The default value is `'light'`, so if the prop is not set, the flyout trigger will look as before.
> feat(refs DPLAN-12969,#AB21841): Add new styling to filter flyout

- CHANGELOG.md
- tests/components/DpFlyout.spec.js
**Related ticket:** [DPLAN-12969](https://demoseurope.youtrack.cloud/issue/DPLAN-12969/ADO-Issue-21841-Admin-Institutionsliste-Institutionen-konnen-nach-Schlagworten-gefiltert-werden)
Adds unit test for DpFlyout. I'm particularly interested in feedback on the first test case, `'renders with expected css classes with default props'` - is this useful? Is there a better way to test it? Do we want to test it at all?
> test(refs DPLAN-12969): add unit test for DpFlyout

- CHANGELOG.md
- src/components/DpTreeList/DpTreeListNode.vue
**Description:** This PR fixes issue when every draggable element (branch or a leaf) has an extra padding bottom.
- add this class only to a branch
- it could be reduced the padding-bottom a bit in the core
!Question: could the padding bottom be added to every draggable branch, to enable dragging elements from one branch to another without expanding it. Should it be possible? Then it could be renamed and added to each branch.. 
It was decided to add padding-bottom to every branch for now and to refactor it later by adding padding on hover. It could be done during further development.
PR in Core: https://github.com/demos-europe/demosplan-core/pull/4281
> fix(DPLAN-12013): styling of draggable element

- CHANGELOG.md
- src/components/DpEditor/libs/preventEditing.js
DPLAN-14659:
Description: added keys to navigate with keyboard to custom tiptap extention preventEditing.js 
Testing:  Verfahren / Abwägungstabelle/ tab to 2. checkbox and check it/ try shift + arrow to mark text
> b-DPLAN-14659: add keys to navigate to preventEditing.js

- CHANGELOG.md
- src/components/DpButtonRow/DpButtonRow.vue
Ticket: https://demoseurope.youtrack.cloud/issue/DPLAN-14948/Aktuelles-Textbaustein-einfugen-moglich-auf-Einfugen-zu-klicken-obwohl-keine-Textbaustein-hinzugefugt-ist
It should be possible to disable only the primary button, because often times it makes sense that the secondary button is still active.
No uses of `DpButtonRow` with disabled prop were found in demosplan-ui.
> bug(refs DPLAN-14948): Add two disabled props for button row

- CHANGELOG.md
- src/components/DpTimePicker/DpTimePicker.vue
[Ticket](https://demoseurope.youtrack.cloud/issue/DPLAN-14980/Verfahrensschritt-automatisch-umstellen-Zeitangabe-undefined)
- Build the time pattern from available hours and minutes to avoid user input that is not allowed.
- Only update time from manual input if it is a valid pattern.
> bug(refs DPLAN-14980): Use dynamic time pattern

- CHANGELOG.md
- src/components/DpTreeList/DpTreeListNode.vue
**Ticket:** https://demoseurope.youtrack.cloud/agiles/141-245/current?issue=DPLAN-15036
**Description:** This PR improves UX: when the treeListNode is empty, it should not be possible to expand it.
> refac(DPLAN-15036): expand the DpTreeListNode only when children exist

- CHANGELOG.md
- src/components/DpButtonRow/DpButtonRow.vue
[Ticket](https://demoseurope.youtrack.cloud/issue/DPLAN-14948/Aktuelles-Textbaustein-einfugen-moglich-auf-Einfugen-zu-klicken-obwohl-keine-Textbaustein-hinzugefugt-ist)
Add option for prop disabled to disable only primary or secondary button or both
Related PR https://github.com/demos-europe/demosplan-ui/pull/1183
> bug(refs DPLAN-14948): Add option for prop disabled 

- CHANGELOG.md
- src/components/DpLabel/DpLabel.vue
**Description:** This PR adjusts the position of the tooltip inside the DpLabel component. There are some layout issues when the hint is provided: the tooltip is placed too far from the label.
before:
after:
> Refac: DpLabel: adjust position of the tooltip and hint

- CHANGELOG.md
- src/components/DpFormRow/DpFormRow.vue
width tailwind we got a new full-width-class wich has to be catched
> fix: Catch Full-width in dpFormRow

- CHANGELOG.md
- src/components/DpEditor/DpEditor.vue
- src/components/DpEditor/libs/editorCustomInsert.js
- src/components/DpEditor/libs/tiptapExtensions.js
Ticket: [DPLAN-15153](https://demoseurope.youtrack.cloud/issue/DPLAN-15153/Benutzer-Menu-Verwalten-und-Plattformtools-Links-funktionieren-nicht-auf-Verfahrenstyp-bearbeiten-Seite)
The workaround for the mention extension import is no longer needed and it is now imported from the correct file in DpEditor.vue.
> fix(refs DPLAN-15153): fix imports for mention extension [vue 3]

- CHANGELOG.md
- src/components/DpButton/DpButton.vue
Using multilines in Js causes \n in the string. They appeard in the classlist, where they dont belong. So we had to escape them
> fix: Escape multiline break chars

- CHANGELOG.md
- src/components/DpEditor/DpEditor.vue
- src/components/DpEditor/DpResizableImage.vue
- src/components/DpEditor/DpUploadModal.vue
- src/components/DpTransitionExpand/DpTransitionExpand.vue
- src/components/DpUploadFiles/DpUpload.vue
- src/components/DpUploadFiles/DpUploadFiles.vue
- src/components/DpUploadFiles/DpUploadedFile.vue
- src/components/DpUploadFiles/DpUploadedFileList.vue
**Ticket:** [DPLAN-15169](https://demoseurope.youtrack.cloud/issue/DPLAN-15169/Nicht-moglich-um-ein-Bild-zu-einem-Kapitel-zu-hinzufugen)
Includes these fixes:
- uppy method `clear()` is used instead of `close()` (which does not exist and threw an error)
- `this.$parent` can't be used in vue 3 anymore and is replaced
- emitted events are now declared (not declaring them may cause problems and is expected in vue 3)
- prop is correctly passed as boolean (instead of string)
- render function in DpTransitionExpand is fixed so that the vue 3 render function api can be enabled, which in turn is needed to make tiptap/vue3 NodeViewWrapper work in DpResizableImage, as it uses the new api.
> fix(refs DPLAN-15169): fix image upload in DpEditor

- CHANGELOG.md
- src/components/DpTreeList/DpTreeList.vue
DPLAN-15161
Add conditional rendering for the DpTreeListToggle component with a new hasContent prop and a computed property for evaluation.
Related PR: https://github.com/demos-europe/demosplan-core/pull/4506
> b(refs: DPLAN-15161) add hasContent props for DpTreeListToggle

- CHANGELOG.md
- package.json
- src/components/DpConfirmDialog/DpConfirmDialog.stories.mdx
- src/components/DpConfirmDialog/DpConfirmDialog.stories.tsx
- src/components/DpConfirmDialog/DpConfirmDialog.vue
- src/components/DpConfirmDialog/index.ts
- src/components/index.js
- src/components/shared/translations.js
**Ticket:** https://demoseurope.youtrack.cloud/issue/DPLAN-15263/Custom-confirm-Dialog-anstelle-des-nativen-Dialogs-window.confirm
**Description:** This PR introduces a new component: `DpConfirmDialog`, which replaces the native window.confirm functionality, as it is not accessible in certain situations (for example, when a user clicks to close all alert messages). DpConfirmDialog is built on the DpModal component.
PR In Core: https://github.com/demos-europe/demosplan-core/pull/4523
> feat(DPLAN-15263): create custom dialog

- CHANGELOG.md
- src/components/DpResettableInput/DpResettableInput.vue
**Ticket:** https://demoseurope.youtrack.cloud/agiles/141-63/current?settings&tab=allgemeines&issue=DPLAN-15342
**Description:** This PR fixes an issue where the `DpResettableInput` was only updated after the second input. It now assigns `this.currentValue = val `when the user inputs text.
There is also a warning about deprecated v-model usage, which I tried to fix, but it does not work as expected. Here is a [thread about the issue](https://demosdeutschland.slack.com/archives/C5BA8ABB2/p1744028862868659). it can be fixed in a separate PR.
> fix(DPLAN-DPLAN-15342): update currentValue when the user inputs text

- CHANGELOG.md
- src/components/DpSearchField/DpSearchField.vue
This got lost with the vue 3 update and is now restored.
See the old PR: https://github.com/demos-europe/demosplan-ui/pull/1147
> fix(refs DPLAN-12969): allow setting the width of the search field

- CHANGELOG.md
- src/components/DpButton/DpButton.vue
To be able to handle `blur`, `focus` and `mousedown` events from DpButton, we need to emit them first.
> feat: emit blur and focus events

- CHANGELOG.md
- src/components/DpDataTable/DpDataTable.vue
**Ticket:** [DPLAN-15338](https://demoseurope.youtrack.cloud/issue/DPLAN-15338/ADO-Issue-26283-Hinzufugen-konfigurierbare-Felder-auf-Abschnittsebene-Part-1-Anlegen)
If we set `headerCellCount` on `beforeUpdate`, the `headerFields` length is still 0, and the `colCount` is not calculated correctly if the table is empty
**Before:**
**After:**
> fix(refs DPLAN-15338, #AB26283): set headerCellCount on mounted

- CHANGELOG.md
- src/components/DpEditor/DpEditor.vue
Change style of 'mark' button to be inline with other buttons. Slightly increase margin towards the caret icon for buttons that open a flyout.
Ticket: [DPLAN-2786](https://demoseurope.youtrack.cloud/issue/DPLAN-2786/Markierungs-Icon-verschoben)
- change of mark button: see ticket
- margin increase: editor buttons with flyout are visible when editing a chapter
> fix(refs DPLAN-2786): adjust editor menu buttons

- CHANGELOG.md
- src/components/DpEditableList/DpEditableList.vue
[DPLAN-15150](https://demoseurope.youtrack.cloud/issue/DPLAN-15150/Support-Items-haben-Edit-und-loschen-Icon-auf-weissem-Hintergrund)
Increased left margin for the second button to ensure the icon is more clearly visible and distinguishable on a white background.
> fix(refs: DPLAN-15150 Increased margin between btns

- CHANGELOG.md
- src/mixins/dpValidateMixin.js
DPLAN-15554
This improves form validation error messages by adding topic names
to field names in error messages. Now, instead of showing only the field names
like "Please correct the following fields: Contact Person, Email Address",
the message will include the topic section names: "Please correct the following
fields: Contact Person (Procedure Information), Email Address (Internal)".-
This enhancement makes it easier for users to find and correct missing
required fields, especially in multi-step forms or wizard interfaces.
How to review
create new procedure, try edit it in "Grundeinstellungen"
the error message should display the corresponding field and topic
Linked PRs
https://github.com/demos-europe/demosplan-core/pull/4655
> feat(refs: DPLAN-15554) basic settings validation 

- CHANGELOG.md
- src/components/DpDataTable/DpDataTable.stories.tsx
- src/components/DpDataTable/DpDataTable.vue
- src/components/DpMultiselect/DpMultiselect.mdx
- src/components/DpMultiselect/DpMultiselect.stories.tsx
- src/components/DpMultiselect/DpMultiselect.vue
- src/mixins/tableSelectAllItems.js
This PR is related to [this one ](https://github.com/demos-europe/demosplan-core/pull/4782). It fixes a bug that got noticed while working on the US. The condition for the 'selectAll' button had to be adjusted to enable it getting disabled when all options have already been selected.
Additionally, it adjusts the names of the custom events relevant to the story to camelCase.
> fix(refs DPLAN-15771, #AB29551): adjust condition for disabled btn

- src/lib/ActionMenu.js
[DPLAN-2798](https://demoseurope.youtrack.cloud/issue/DPLAN-2798)
This PR adjusts the behavior of the action menu so that it can be properly used with a keyboard according to accessibility guidelines. You can now use enter and space to open it and tab/ shift + tab to navigate inside it. The actionmenu was added to the header flyout of diplanbau, -rog and -fest in the linked PRs.
rog: [200](https://github.com/demos-europe/demosplan-project-diplanrog/pull/200)
fest: [143](https://github.com/demos-europe/demosplan-project-diplanfest/pull/143)
bau: [313](https://github.com/demos-europe/demosplan-project-diplanbau/pull/313)
> fix(refs DPLAN-2798): adjust actionmenu behavior for tab and enter key

- CHANGELOG.md
- tsconfig.json
otherwise we get some issues resolving esm only dependencies. and in the End this is the more correct setting anyway
for further details see
https://www.typescriptlang.org/docs/handbook/modules/theory.html#module-resolution-for-bundlers-typescript-runtimes-and-nodejs-loaders
And it fixes an issue where useSortable is not importable after bumping vueUse to 13.
> chore: Change TS config moduleResolution to bundler

- CHANGELOG.md
- src/components/DpInput/DpInput.vue
**Ticket:** [DPLAN-16037](https://demoseurope.youtrack.cloud/issue/DPLAN-16037) Nicht möglich um Berechtigte Absenderadressen für den E-Mail Import zu editieren oder löschen
**Description:**  In Vue 3 `v-model` on custom components no longer uses the native `value/input` API, it binds to a `modelValue` prop and emits `update:modelValue`. This change explicitly declares that mapping (using `defineOptions` in `<script setup>`) so that v-model works correctly on our custom inputs under compat mode.
> fix(DPLAN-16037): restore Vue 3 v-model for DpInput

- Dockerfile
- Fixes CI permission error when node user tries to write to package.json during yarn install
- Ensures the working directory is owned by node:node before switching to the node user
> fix: set proper permissions for /app directory in Dockerfile

- CHANGELOG.md
- src/components/DpFlyout/DpFlyout.vue
- src/components/DpResettableInput/DpResettableInput.vue
[DPLAN-16159](https://demoseurope.youtrack.cloud/issue/DPLAN-16159)
This PR adds a prop to control whether the DpFlyout trigger has position: relative or absolute and fixes the logic for detection whether DpResettableInput has meaningful slot content. Returning 'false' for fragments was incorrect since these can contain meaningful nodes in Vue.
Related PR in Core: [4968](https://github.com/demos-europe/demosplan-core/pull/4968)
> B dplan 16159 fix search field

- CHANGELOG.md
- src/components/DpAccordion/DpAccordion.vue
[DPLAN-16160](https://demoseurope.youtrack.cloud/issue/DPLAN-16160/Mitzeichnende-Toggle-ist-verrutscht-und-wenn-man-darauf-klickt-wird-das-STN-Formular-submitted)
This PR adjusts the changes made in the following PR:
https://github.com/demos-europe/demosplan-ui/pull/1269/files
- it re-adds the type of 'button' to remove the default submit behaviour when DpAccordion is inside a form
- adjusts Tailwind classes
Related PR in demosplan-core: https://github.com/demos-europe/demosplan-core/pull/4963
(Adds padding left in the side menu --> with the new position of the caret icon (after the text), the text in the side menu was too far left)
> fix(refs dplan-16160): Remove default submit behaviour and adjust styles

- CHANGELOG.md
- src/components/DpNotification/DpNotification.vue
[DPLAN-14969](https://demoseurope.youtrack.cloud/issue/DPLAN-14969/ADO-Issue-23560-Rechtzeitige-Ankundigung-Ausloggen-damit-gespeichert-werden-kann)
So far, only the notifications of type 'error' were not set to disappear after 20 seconds.
This PR expands the condition for the DpNotification setTimeout, so that other types of notifications (warning, info) can also be allowed to persist, if needed.
'message.persist' is implemented as optional (and defaults to 'false'), so that already existing implementations are not affected.
Related core-PRs: 
FE: https://github.com/demos-europe/demosplan-core/pull/4970
BE: https://github.com/demos-europe/demosplan-core/pull/4959
> feat(refs DPLAN-14969, #AB23560): Allow non-error DpNotification MSGs to persist

- CHANGELOG.md
- package.json
- yarn.lock
[DPLAN-16207](https://demoseurope.youtrack.cloud/issue/DPLAN-16207)
This PR adds more prosemirror packages to the resolutions in the package.json. The error in the ticket was caused by different versions of prosemirror packages being imported, since some of them have other prosemirror packages as dependencies themselves, and it appears that not all versions are compatible with each other. The "resolutions" section of the package.json is referenced by yarn to resolve these version conflicts and ensure that only one version is imported. 
1. Login as admin in a project that has segments and navigate to the 'Stellungnahmen aufteilen' section.
2. Start to create a segment, add a tag to it, and then abort the process with the abort button.
3. Test if there is any weird behavior now like being …
> fix(refs DPLAN-16159): add more prosemirror packages to resolutions

- src/components/DpCheckboxGroup/DpCheckboxGroup.vue
- tests/form/DpCheckboxGroup.spec.js
This PR adds unit tests for DpCheckboxGroup.
I also discovered a bug in DpCheckboxGroup: On mount, selected was set to false for every option, regardless of whether 'true' was passed via the selectedOptions prop. I included a fix in this PR.
> feat: add tests for DpCheckboxGroup

- CHANGELOG.md
- src/components/index.js
- src/mixins/dpValidateMixin.js
**Ticket:** [DPLAN-16416](https://demoseurope.youtrack.cloud/issue/DPLAN-16416) Fehler wenn man eine PDF unter Antragsunterlagen hochladen probiert
**Description:**
This PR fixes an issue (`Uncaught TypeError: Cannot read properties of undefined (reading 'error') at Proxy.dpValidateAction`) in the addon. The problem occurs because the dpValidateMixin has been duplicated in the addon and requires access to the `de` object from the UI library.
> Fix(dplan-16416): error - de is undefined

- src/components/DpRadio/DpRadio.vue
- tests/form/DpRadio.spec.js
This PR adds tests for the DpRadio component.
It also adjusts the data-cy value to 'null' instead of 'false', because the Attribute Coercion Behaviour changed with Vue3 --> attribute is no longer removed if the value is boolean false. Instead, it's set as attr="false". To remove the attribute, null or undefined has to be used. (https://v3-migration.vuejs.org/breaking-changes/attribute-coercion)
> test: Add tests for DpRadio
