demos-europe/demosplan-ui

package.json

Since "postinstall" looks like the wrong hook. Lets try "postcompress"

fix: Change Hook to build dist

---

src/components/core/DpModal.vue

Description: In assessment table in the page of original statement the console shows some errors. the problem could be that the root element is empty, so we need a condition to fix this problem. Anyway I couldnt test it yet, if it works this way

Fix: Set a condition if the root element is empty WIP

---

webpack.config.js
yarn.lock

Reverts demos-europe/demosplan-ui#55
This shall be fixed in demosplan-core

Revert "fix(refs T30430): Add tiptap to externals"

---

src/components/core/DpEditor/DpResizableImage.vue

it somehow causes an error of undefined Translator. I Think this is not the underlying issue, but changing this helps me to get closer to the real problem

fix(refs T31010): Don't use Translator directly in template

---

CHANGELOG.md

Add changes to changelog hence they have been forgotten

chore: write Changelog

---

CHANGELOG.md
package.json
src/components/core/DpDataTable/DpDataTable.vue

When using DpTable it happend, that the DpDraggable Component could not be resolved when loaded lazy.
refs https://yaits.demos-deutschland.de/T31324

fix(refs T31324): Don't load DpDraggable async in DpDataTable

---

tokens/color.json

https://yaits.demos-deutschland.de/T30974
- Add (light-4) value for brand main.

chore (refs T30974): Add (light-4) value for brand main.

---

tokens/color.json
tokens/color.stories.mdx

To be able to cleanup color variables, finally all needed tokens are crafted based on the current color palettes.

Add message tokens

---

CHANGELOG.md
src/components/DpDatepicker/DpDatepicker.vue

This reverts commit cca9f4219b62ceb786a74e5899b22f44ac01989a.

fix: Revert "fix(refs T31929): Load cjs package instead of es"

---

src/components/DpInput/DpInput.vue

in preparation for vue3 we have to prevent size from beeing able to be 0

chore(refs T32012): Prevent size from being 0

---

CHANGELOG.md

feat: add changelog entry 

---

src/components/DpMultiselect/DpMultiselect.vue
src/lib/validation/dpValidateMultiselectDirective.js

In vue3 functional components doesn't work. So we have to migrate them all to template-components.
Starting with dpMultiselect

chore(refs T32012): unFunctional Multiselect

---

CHANGELOG.md
src/components/core/DpDataTable/DpDataTableExtended.vue
src/components/core/DpDataTable/DpSelectPageItemCount.vue

I forgot to commit that in the original PR and no one noticed.
This Change is necessary that the trans key get passed properly
And the missing Changelog entry of course.
see here github.com/demos-europe/demosplan-ui/pull/195

Fix(refs T19787, T19759): Pass propper Prop 

---

CHANGELOG.md
src/components/DpContextualHelp/DpContextualHelp.vue

unFunctional Component and Move Template from Render to Template

chore(refs T19787, T19759): Rebuild template for DpContextualHelp

---

CHANGELOG.md

Description: Add comments to the changelog regarding the migration of DpTableRow, DpDataTable, and DpTableHeader to template-based components

feat(T19759): DpDataTable: add comments to the changelog

---

CHANGELOG.md

https://yaits.demos-deutschland.de/T30980
- remove some component class, to pass it from outside.
https://github.com/demos-europe/demosplan-core/pull/1604

chore (refs T30980): add changelog.

---

CHANGELOG.md
src/components/DpFormRow/DpFormRow.vue

https://yaits.demos-deutschland.de/T30980
- remove class, to pass it from outside.
https://github.com/demos-europe/demosplan-core/pull/1609

chore (refs T30980): remove class, to pass it from outside.

---

CHANGELOG.md
src/components/core/DpBulkEditHeader.vue

https://yaits.demos-deutschland.de/T30980
- remove spacing & layout classes.

chore (refs T30980): remove spacing & layout classes.

---

CHANGELOG.md
src/components/DpDataTable/DpDataTableExtended.vue

https://yaits.demos-deutschland.de/T30980
- remove spacing class.

chore (refs T30980): remove spacing class.

---

src/components/DpSelect/DpSelect.stories.mdx
src/components/DpSelect/DpSelect.vue

https://yaits.demos-deutschland.de/T33318
- add storybook for DpSelect component.

chore (refs T33323): add storybook for DpSelect component.

---

CHANGELOG.md
src/components/DpRadio/DpRadio.stories.mdx

https://yaits.demos-deutschland.de/T33316
- add DpRadio to storybook.

chore (refs T33316): add DpRadio to storybook.

---

src/components/DpCard/DpCard.vue
src/components/DpFlyout/DpFlyout.vue
tokens/src/rounded.json
tokens/tokens._overview.stories.mdx
tokens/tokens.boxShadow.stories.mdx
tokens/tokens.breakpoints.stories.mdx
tokens/tokens.rounded.stories.mdx
tokens/tokens.zIndex.stories.mdx

As Tailwind utilities are only helpful when documented, here we go.

Add more docs on tailwind

---

src/components/DpAccordion/DpAccordion.mdx
src/components/DpAccordion/DpAccordion.stories.tsx

- Migrate DpAccordion stories to v7.

F upgrade storybook migrate dp accordion

---

src/components/DpAccordion/DpAccordion.stories.mdx
src/components/DpAccordion/DpAccordion.stories.tsx
src/components/DpAutocomplete/DpAutocomplete.stories.mdx
src/components/DpAutocomplete/DpAutocomplete.stories.tsx
src/components/DpAutocomplete/DpAutocomplete.vue
src/components/DpContextualHelp/DpContextualHelp.stories.mdx
src/components/DpContextualHelp/DpContextualHelp.stories.tsx
src/components/DpFlyout/DpFlyout.stories.mdx
src/components/DpFlyout/DpFlyout.stories.tsx
src/components/DpHeightLimit/DpHeightLimit.stories.mdx
src/components/DpHeightLimit/DpHeightLimit.stories.tsx
src/components/shared/translations.js

- Migrate DpAutocomplete stories to v7.
- remove Translator.trans from DpAutocomplete

F upgrade storybook migrate dp autocomplete

---

src/components/DpLoading/DpLoading.stories.mdx
src/components/DpLoading/DpLoading.stories.tsx

- Migrate DpLoading story to v7.

F upgrade storybook migrate dp loading

---

src/components/DpRadio/DpRadio.stories.mdx
src/components/DpRadio/DpRadio.stories.tsx

- Migrate DpRadio stories to v7.

F upgrade storybook migrate dp radio

---

src/components/DpDataTable/DpDataTable.stories.mdx
src/components/DpDataTable/DpDataTable.stories.tsx
src/components/DpDataTable/DpDataTable.vue
src/components/shared/translations.js

- Migrate DpDataTable stories to v7.
- Add Trans-Key.

chore: Migrate DpDataTable stories to v7.

---

CHANGELOG.md
src/components/DpSplitButton/DpSplitButton.vue

https://yaits.demos-deutschland.de/T33945
https://github.com/demos-europe/demosplan-core/pull/1855
- add missing Hooks/Selectors.

chore (refs T33945): add missing Hooks/Selectors.

---

CHANGELOG.md
src/components/DpAccordion/DpAccordion.vue

https://yaits.demos-deutschland.de/T34037
- add E2E Prop.

chore (refs T34037): add E2E Prop.

---

src/components/DpToggle/DpToggle.mdx
src/components/DpToggle/DpToggle.stories.mdx
src/components/DpToggle/DpToggle.stories.tsx
src/components/shared/translations.js

- Migrate DpToggle stories to v7.
- adjust Trans-Key.

F upgrade storybook migrate dp toggle

---

src/components/DpPager/DpPager.stories.mdx
src/components/DpPager/DpPager.stories.tsx

- Migrate DpPager stories to v7.

 chore: Migrate DpPager stories to v7.

---

tests/__snapshots__/DpContextualHelp.spec.js.snap

sadly i forgot to run jest before merging https://github.com/demos-europe/demosplan-ui/pull/462

fix: update snapshot after changing markup

---

src/components/DpResettableInput/DpResettableInput.stories.mdx
src/components/DpResettableInput/DpResettableInput.stories.tsx

- Migrate DpResettableInput stories to v7.

 chore: Migrate DpResettableInput stories to v7.

---

CHANGELOG.md
src/components/DpCard/DpCard.stories.mdx
src/components/DpCard/DpCard.stories.tsx

- migrate DpCard to Storybook 7.

chore: migrate DpCard to Storybook 7.

---

CHANGELOG.md
src/components/DpCheckboxGroup/DpCheckboxGroup.stories.mdx
src/components/DpCheckboxGroup/DpCheckboxGroup.stories.tsx
src/components/DpCheckboxGroup/DpCheckboxGroup.vue

- Add DpCheckboxGroup to Storybook.

chore: Add DpCheckboxGroup to Storybook.

---

CHANGELOG.md
src/components/DpInlineNotification/DpInlineNotification.stories.mdx
src/components/DpInlineNotification/DpInlineNotification.stories.tsx

- add DpInlineNotification to Storybook.

chore: add DpInlineNotification to Storybook.

---

CHANGELOG.md
src/components/DpSkeletonBox/DpSkeletonBox.stories.mdx
src/components/DpSkeletonBox/DpSkeletonBox.stories.tsx

- add DpSkeletonBox to Storybook.

chore: add DpSkeletonBox to Storybook.

---

CHANGELOG.md
package.json
src/components/DpAccordion/DpAccordion.stories.tsx
src/components/DpAutocomplete/DpAutocomplete.stories.tsx
src/components/DpButtonRow/DpButtonRow.stories.tsx
src/components/DpCard/DpCard.stories.tsx
src/components/DpCheckbox/DpCheckbox.stories.tsx
src/components/DpCheckboxGroup/DpCheckboxGroup.stories.tsx
src/components/DpDataTable/DpColumnSelector.stories.tsx
src/components/DpDataTable/DpDataTable.stories.tsx
src/components/DpDetails/DpDetails.stories.tsx
src/components/DpFlyout/DpFlyout.stories.tsx
src/components/DpHeightLimit/DpHeightLimit.stories.tsx
src/components/DpIcon/DpIcon.stories.tsx
src/components/DpInlineNotification/DpInlineNotification.stories.mdx
src/components/DpInlineNotification/DpInlineNotification.stories.tsx
src/components/DpInput/DpInput.stories.tsx
src/components/DpLabel/DpLabel.stories.tsx
src/components/DpLoading/DpLoading.stories.tsx
src/components/DpMultiselect/DpMultiselect.stories.tsx
src/components/DpMultistepNav/DpMultistepNav.stories.tsx
src/components/DpPager/DpPager.stories.tsx
src/components/DpRadio/DpRadio.stories.tsx
src/components/DpResettableInput/DpResettableInput.stories.tsx
src/components/DpSelect/DpSelect.stories.tsx
src/components/DpSlidebar/DpSlidebar.stories.tsx
src/components/DpTabs/DpTabs.stories.tsx
src/components/DpToggle/DpToggle.stories.tsx
src/components/DpTooltipIcon/DpTooltipIcon.stories.tsx
yarn.lock

Typescript prevented Storybook from building without errors.
Here are the fixes.

fix: Adjust storybook

---

CHANGELOG.md
src/components/DpSplitButton/DpSplitButton.stories.mdx
src/components/DpSplitButton/DpSplitButton.stories.tsx

- add DpSplitButton to Storybook.

chore: add DpSplitButton to Storybook.

---

src/components/DpAccordion/DpAccordion.stories.tsx
src/components/DpBadge/DpBadge.stories.tsx
src/components/DpSelect/DpSelect.stories.mdx

https://github.com/demos-europe/demosplan-ui/pull/483
- fix Storybook errors.

fix: fix Storybook errors.

---

package.json
yarn.lock

- fix storybook errors, update version.
for test:
`yarn install` ->` yarn storybook`

fix: fix storybook errors, update version.

---

CHANGELOG.md
src/components/DpSlidingPagination/DpSlidingPagination.stories.mdx
src/components/DpSlidingPagination/DpSlidingPagination.stories.tsx

- add DpSlidingPagination to Storybook.

chore: add DpSlidingPagination to Storybook.

---

CHANGELOG.md
src/components/DpTooltip/DpTooltip.stories.mdx
src/components/DpTooltip/DpTooltip.stories.tsx

- add DpTooltip to Storybook.
- fix Tooltip container id.

chore: add DpTooltip to Storybook.

---

CHANGELOG.md
src/components/core/DpUpload/DpUpload.vue
src/components/core/DpUpload/DpUploadFiles.vue
src/components/core/DpUpload/utils/UppyTranslations.js
src/components/shared/translations.js

https://github.com/demos-europe/demosplan-core/pull/1982
https://demosdeutschland.slack.com/archives/C5BA8ABB2/p1694073669036689
- Add Props to DpUpload & DpUploadFiles.
- Add de Trans-Key
- Adjust UppyTranslations.

chore: add Props to DpUpload & DpUploadFiles.

---

src/components/DpDatepicker/DpDatepicker.stories.mdx
src/components/DpDatepicker/DpDatepicker.stories.tsx
src/components/DpDatepicker/DpDatepicker.vue

- add DpDatepicker to Storybook.

chore: add DpDatepicker to Storybook.

---

CHANGELOG.md
src/components/DpButtonIcon/DpButtonIcon.stories.mdx
src/components/DpButtonIcon/DpButtonIcon.stories.tsx
src/components/DpButtonIcon/DpButtonIcon.vue

- add DpButtonIcon to Storybook.

chore: add DpButtonIcon to Storybook.

---

CHANGELOG.md
src/components/DpTimePicker/DpTimePicker.stories.mdx
src/components/DpTimePicker/DpTimePicker.stories.tsx

- add DpTimePicker to Storybook.

chore: add DpTimePicker to Storybook.

---

CHANGELOG.md
src/components/DpProgressBar/DpProgressBar.stories.mdx
src/components/DpProgressBar/DpProgressBar.stories.tsx

- add DpProgressBar to Storybook.

chore: add DpProgressBar to Storybook.

---

src/components/DpModal/DpModal.stories.mdx
src/components/DpModal/DpModal.stories.tsx
src/components/DpModal/DpModal.vue

- WIP: Add DpModal to Storybook
- Fix getComputedStyle error `Window.getComputedStyle: Argument 1 does not implement interface Element.`, adjust DpModal Storybook.

chore: WIP: Add DpModal to Storybook

---

src/components/DpTextArea/DpTextArea.stories.tsx

- fix args error in DpTextArea.

chore: fix args error in DpTextArea.

---

CHANGELOG.md
src/components/DpTreeList/DpTreeList.stories.mdx
src/components/DpTreeList/DpTreeList.stories.tsx
src/components/DpTreeList/DpTreeListCheckbox.vue
src/components/DpTreeList/DpTreeListToggle.vue
src/components/shared/translations.js

- WIP: Add DpTreeList to Storybook.
- Add de Trans-Key for DpTreeListToggle.

Add dp tree list to storybook

---

package.json
yarn.lock

As recommended in https://github.com/storybookjs/storybook/issues/22431#issuecomment-1630086092 rebuilding yarn.lock seems to fix the bug described in the ticket. As a side effect, some patch updates were applied.

fix: rebuild yarn.lock

---

tests/DpTreeListCheckbox.spec.js

https://demosdeutschland.slack.com/archives/C5BA8ABB2/p1699349147948769
- Fix DpTreeListCheckbox Test.

chore: Fix DpTreeListCheckbox Test.

---

CHANGELOG.md
src/components/core/DpEditor/DpEditor.vue

setContent is part of commands.

fix: Use proper method to reset content in DPEditor

---

CHANGELOG.md
src/components/core/DpEditableList.stories.tsx

chore: fix prod build

---

.storybook/main.js
CHANGELOG.md
package.json
src/components/DpAccordion/DpAccordion.vue
src/components/DpButton/DpButton.vue
src/components/DpMultiselect/DpMultiselect.vue
src/components/core/DpEditableList.stories.tsx
src/components/core/DpEditor/DpEditor.vue
src/lib/DpApi.js
yarn.lock

merge main into i_vue3_migration

---

src/components/DpDatetimePicker/DpDatetimePicker.vue
src/components/DpTextArea/DpTextArea.vue

https://yaits.demos-deutschland.de/T19785
Integration PR: https://github.com/demos-europe/demosplan-ui/pull/575
Core: https://github.com/demos-europe/demosplan-core/pull/2424
- add defineAsyncComponent to async components.

chore (refs T19785): add defineAsyncComponent to async components.

---

src/components/DpEditor/DpEditor.vue
src/directives/Tooltip/Tooltip.stories.mdx

`float--right` has been changed to the Tailwind `float-right`.

Use correct class name

---

CHANGELOG.md
src/components/DpMultiselect/DpMultiselect.vue

We also need to pass the prop to vue multiselect.

bug: Fix required for multiselect

---

src/components/DpTransitionExpand/DpTransitionExpand.vue

https://yaits.demos-deutschland.de/T19759
https://yaits.demos-deutschland.de/T19784
- migration render function to Vue3.

chore (refs T19759 T19784): migration render function to Vue3.

---

src/components/DpButtonRow/DpButtonRow.vue

https://yaits.demos-deutschland.de/T34245
- Add missing Hooks/Selectors.

chore (refs T34245): Add missing Hooks/Selectors.

---

CHANGELOG.md
src/components/DpVideoPlayer/DpVideoPlayer.vue

Replaces https://github.com/demos-europe/demosplan-ui/pull/785 which was not an actual fix

fix(refs T36651): make plyr import work

---

CHANGELOG.md
src/components/DpDataTable/DpDataTable.vue
src/components/DpDataTable/DpTableHeader.vue
src/components/DpDataTable/DpTableRow.vue
src/components/DpResettableInput/DpResettableInput.vue

https://yaits.demos-deutschland.de/T36838
https://github.com/demos-europe/demosplan-core/pull/2877
https://yaits.demos-deutschland.de/T36838#872739
- add E-2-E Test Props.

chore (refs T36838): add E-2-E Test Props.

---

CHANGELOG.md
src/components/DpDataTable/DpTableHeader.vue
src/components/DpDataTable/DpTableRow.vue
src/components/DpDataTable/DpWrapTrigger.vue

https://yaits.demos-deutschland.de/T36853
https://demoseurope.youtrack.cloud/issue/DPP-2744/Missing-Hooks-Fur-Stellungnahme-Tabelle
- add missing Props.

chore (refs T36853): add missing Props.

---

CHANGELOG.md
src/components/DpUploadFiles/DpUpload.vue

https://demoseurope.youtrack.cloud/issue/DPLAN-3254
- Add data-cy for hidden input element.
- that accepted files array.

chore (refs DPLAN-3254): add data-cy for hidden input element.

---

CHANGELOG.md
src/components/DpCard/DpCard.vue
src/components/DpContextualHelp/DpContextualHelp.vue

https://demoseurope.youtrack.cloud/issue/DPLAN-11413
https://demosdeutschland.slack.com/archives/C5BA8ABB2/p1712828931605029?thread_ts=1712665548.061619&cid=C5BA8ABB2
- adjust DpCard Styling.
Before:
After:

chore (refs DPLAN-11413): adjust DpCard Styling.

---

CHANGELOG.md
tailwind.config.js

This utility is needed for a custom scrollbar solution in demosplan-core.

Add .scrollbar-none utility

---

CHANGELOG.md
src/components/DpEditableList/DpEditableList.vue

https://demoseurope.youtrack.cloud/issue/DPLAN-11504
Core PR: https://github.com/demos-europe/demosplan-core/pull/3152
- Adjust data-cy Hooks/Selectors.

chore (refs DPLAN-11504): Adjust data-cy Hooks/Selectors.

---

src/components/DpDataTableExtended/DpDataTableExtended.vue

Ticket: https://demoseurope.youtrack.cloud/issue/DPLAN-11601
Add translations prop to pass on to DpDataTable.
Related PR https://github.com/demos-europe/demosplan-core/pull/3175

feat(refs DPLAN-11601): Add translations as prop

---

CHANGELOG.md

Update changelog for https://github.com/demos-europe/demosplan-ui/pull/879

feat(refs DPLAN-11601): Update changelog

---

CHANGELOG.md
src/components/DpDataTableExtended/DpDataTableExtended.vue
src/components/DpDataTableExtended/DpSelectPageItemCount.vue

https://demoseurope.youtrack.cloud/issue/DPLAN-11743/Hooks-Institution-verwalten-und-via-Email-einladen-Unregistrierte-Institution
- Add missing Hooks/Selectors.

chore (refs DPLAN-11743): Add missing Hooks.

---

CHANGELOG.md
src/components/DpDetails/DpDetails.vue

https://demoseurope.youtrack.cloud/issue/DPLAN-11769/Hooks-Organisation-verwalten
- Add missing E-2-E Test Props.

chore (refs DPLAN-11769): Add missing E-2-E Test Props.

---

CHANGELOG.md
src/components/DpDataTable/DpDataTable.vue

https://demoseurope.youtrack.cloud/issue/DPLAN-3485/Hooks-Abschnitte
- Add missing Hooks/Selectors.

chore (refs DPLAN-3485): Add missing Hooks/Selectors.

---

CHANGELOG.md
src/components/DpButtonRow/DpButtonRow.vue

https://demoseurope.youtrack.cloud/issue/DPLAN-11820/Hooks-Plattform-Einstellungen-Page
- Add E-2-E Prop.

 chore (refs DPLAN-11820): Add E-2-E Prop.

---

CHANGELOG.md
src/components/DpBulkEditHeader/DpBulkEditHeader.vue

https://demoseurope.youtrack.cloud/issue/DPLAN-12005
- add missing Hook.

 chore (refs DPLAN-12005): add missing Hook.

---

CHANGELOG.md
src/components/DpInlineNotification/DpInlineNotification.vue

https://demoseurope.youtrack.cloud/issue/DPLAN-12028/Hooks-fur-Bearbeitungsschritte-Page
https://demoseurope.youtrack.cloud/issue/DPLAN-12029/Hooks-fur-Token-und-Token-Container
- Add missing Hooks Prop.

fix (refs DPLAN-12028, DPLAN-12029): Add missing Hooks Prop.

---

CHANGELOG.md
src/components/DpTreeList/DpTreeList.vue
src/components/DpTreeList/DpTreeListNode.vue

https://demoseurope.youtrack.cloud/issue/DPLAN-12078
- Add missing Hooks.

fix (refs DPLAN-12078): Add missing Hooks.

---

tests/DpFlyout.spec.js

https://demoseurope.youtrack.cloud/issue/DPLAN-11885/Unit-Tests-schreiben
- Add Jest Test for the DpFlyout component.

chor (refs DPLAN-11885): Add Jest Test for the DpFlyout component.

---

CHANGELOG.md
src/utils/formatString.js
src/utils/index.js
tests/utils/date.test.js
tests/utils/debounce.test.js
tests/utils/deepMerge.test.js
tests/utils/formatBytes.test.js
tests/utils/formatString.test.js
tests/utils/hasOwnProp.test.js
tests/utils/hasPermission.test.js
tests/utils/sortAlphabetically.test.js
tests/utils/uniqueArrayByObjectKey.test.js

**Description:** This PR adds `formatString` utility and adds unit tests for the `capitalizeFirstLetter` function.
PR in core: https://github.com/demos-europe/demosplan-core/pull/3730

feat: add formatString utility

---

CHANGELOG.md
src/utils/formatString.js
src/utils/index.js
tests/utils/date.test.js
tests/utils/debounce.test.js
tests/utils/deepMerge.test.js
tests/utils/formatBytes.test.js
tests/utils/formatString.test.js
tests/utils/hasOwnProp.test.js
tests/utils/hasPermission.test.js
tests/utils/sortAlphabetically.test.js
tests/utils/uniqueArrayByObjectKey.test.js

**Description:** This PR adds `capitalizeFirstLetter` utility function and unit tests for it.
This is a [copy](https://github.com/demos-europe/demosplan-ui/pull/1029) for the main branch.
PR in core: https://github.com/demos-europe/demosplan-core/pull/3730

feat: add capitalizeFirstLetter utility func

---

CHANGELOG.md
package.json
yarn.lock

fix: move 'vue' from peerDep to devDep; add @tiptap/extension-text-style to fix dep. issue

fix: some adjustments after the change to yarn 4.2.2

---

CHANGELOG.md
src/components/DpToggle/DpToggle.vue
src/components/DpTreeList/DpTreeList.vue

Configure Option to deny drag/dropping on rootlevel
(and one minor adjustment)

fix(refs dplan-12315): Configure Option to deny drag/dropping on rootlevel

---

CHANGELOG.md
src/components/DpButton/DpButton.vue
src/components/DpInput/DpInput.vue
src/components/DpLabel/DpLabel.vue
src/components/DpSelect/DpSelect.vue
src/components/DpTextArea/DpTextArea.vue

- Fix the determination for defining if dpButton is a button or a link
- add hover-styles to make the button-styled Link looks good
- Adjust Input spacing which for some reason doesn't fit anymore
- a little type scripting

fix: DpButton as Link and Input spacing 

---

CHANGELOG.md
docker-compose.local.yml
package.json

chore: bump min node to 20.18.1

---

CHANGELOG.md
src/components/DpSearchField/DpSearchField.vue

Related Ticket: [DPLAN-12969](https://demoseurope.youtrack.cloud/issue/DPLAN-12969/ADO-Issue-21841-Admin-Institutionsliste-Institutionen-konnen-nach-Schlagworten-gefiltert-werden)

fix(refs DPLAN-12969): Allow setting the width of the search field

---

CHANGELOG.md
package.json
yarn.lock

the build did not work because a dependency was missing

build: add missing dependency [vue 3]

---

CHANGELOG.md
src/components/DpResettableInput/DpResettableInput.vue
src/components/DpSearchField/DpSearchField.vue
tests/DpSearchField.spec.js

Changes from https://github.com/demos-europe/demosplan-ui/pull/1133 adapted for the vue3-version of demosplan-ui

feat(refs DPLAN-12968): introduce condensed search field [vue 3]

---

CHANGELOG.md
src/components/DpInput/DpInput.vue
src/components/DpLabel/DpLabel.vue

Ticket
DPLAN-12869
Description: Added isDisabled prop to DpLabel to change cursor from pointer to auto when input is disabled.
How to review/test
Login/ Click on user icon choose "Mein Profil" or Organization
PR: https://github.com/demos-europe/demosplan-project-diplanbau/pull/275

b-DPLAN-12869: add idDisabled prop to dl-label to change cursor style

---

CHANGELOG.md
src/components/DpEditor/DpEditor.vue

DPLAN-12502 wrong icon alignment
added inline-block

B dplan 12502 wrong icon alignment

---

CHANGELOG.md
src/components/DpDataTable/DpTableRow.vue
src/components/DpFlyout/DpFlyout.vue

chore: Implement Changes done in 0.3.x

---

CHANGELOG.md
src/components/DpDataTable/DpWrapTrigger.vue

b(refs: DPLAN-15157) wrong icon

---

CHANGELOG.md
src/components/DpEditor/DpEditor.vue

DPLAN-13110
changed emitValue to pass obscure tag

b(refs: DPLAN-13110) changed emitvalue to pass obscure tag

---

CHANGELOG.md
src/components/DpFlyout/DpFlyout.vue
src/components/DpResettableInput/DpResettableInput.vue

Ticket
DPLAN-15410
Add padding to align trigger flyout btn and add some spacing to reset btn

b(refs: DPLAN-15410) add padding to align trigger flyout btn

---

CHANGELOG.md
src/components/DpEditor/DpEditor.vue
src/components/shared/translations.js

DPLAN-15440
Adjusted the headingLevel function to expect an object with a level property.

b(refs: DPLAN-15440) Adjusted the headingLevel function 
